// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: bpfrx.proto

package bpfrxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BpfrxService_EnterConfigure_FullMethodName            = "/bpfrx.v1.BpfrxService/EnterConfigure"
	BpfrxService_ExitConfigure_FullMethodName             = "/bpfrx.v1.BpfrxService/ExitConfigure"
	BpfrxService_GetConfigModeStatus_FullMethodName       = "/bpfrx.v1.BpfrxService/GetConfigModeStatus"
	BpfrxService_Set_FullMethodName                       = "/bpfrx.v1.BpfrxService/Set"
	BpfrxService_Delete_FullMethodName                    = "/bpfrx.v1.BpfrxService/Delete"
	BpfrxService_Commit_FullMethodName                    = "/bpfrx.v1.BpfrxService/Commit"
	BpfrxService_CommitCheck_FullMethodName               = "/bpfrx.v1.BpfrxService/CommitCheck"
	BpfrxService_CommitConfirmed_FullMethodName           = "/bpfrx.v1.BpfrxService/CommitConfirmed"
	BpfrxService_ConfirmCommit_FullMethodName             = "/bpfrx.v1.BpfrxService/ConfirmCommit"
	BpfrxService_Rollback_FullMethodName                  = "/bpfrx.v1.BpfrxService/Rollback"
	BpfrxService_ShowConfig_FullMethodName                = "/bpfrx.v1.BpfrxService/ShowConfig"
	BpfrxService_ShowCompare_FullMethodName               = "/bpfrx.v1.BpfrxService/ShowCompare"
	BpfrxService_ShowRollback_FullMethodName              = "/bpfrx.v1.BpfrxService/ShowRollback"
	BpfrxService_ListHistory_FullMethodName               = "/bpfrx.v1.BpfrxService/ListHistory"
	BpfrxService_GetStatus_FullMethodName                 = "/bpfrx.v1.BpfrxService/GetStatus"
	BpfrxService_GetGlobalStats_FullMethodName            = "/bpfrx.v1.BpfrxService/GetGlobalStats"
	BpfrxService_GetZones_FullMethodName                  = "/bpfrx.v1.BpfrxService/GetZones"
	BpfrxService_GetPolicies_FullMethodName               = "/bpfrx.v1.BpfrxService/GetPolicies"
	BpfrxService_GetSessions_FullMethodName               = "/bpfrx.v1.BpfrxService/GetSessions"
	BpfrxService_GetSessionSummary_FullMethodName         = "/bpfrx.v1.BpfrxService/GetSessionSummary"
	BpfrxService_GetNATSource_FullMethodName              = "/bpfrx.v1.BpfrxService/GetNATSource"
	BpfrxService_GetNATDestination_FullMethodName         = "/bpfrx.v1.BpfrxService/GetNATDestination"
	BpfrxService_GetScreen_FullMethodName                 = "/bpfrx.v1.BpfrxService/GetScreen"
	BpfrxService_GetEvents_FullMethodName                 = "/bpfrx.v1.BpfrxService/GetEvents"
	BpfrxService_GetInterfaces_FullMethodName             = "/bpfrx.v1.BpfrxService/GetInterfaces"
	BpfrxService_ShowInterfacesDetail_FullMethodName      = "/bpfrx.v1.BpfrxService/ShowInterfacesDetail"
	BpfrxService_GetDHCPLeases_FullMethodName             = "/bpfrx.v1.BpfrxService/GetDHCPLeases"
	BpfrxService_GetDHCPClientIdentifiers_FullMethodName  = "/bpfrx.v1.BpfrxService/GetDHCPClientIdentifiers"
	BpfrxService_GetRoutes_FullMethodName                 = "/bpfrx.v1.BpfrxService/GetRoutes"
	BpfrxService_GetOSPFStatus_FullMethodName             = "/bpfrx.v1.BpfrxService/GetOSPFStatus"
	BpfrxService_GetBGPStatus_FullMethodName              = "/bpfrx.v1.BpfrxService/GetBGPStatus"
	BpfrxService_GetIPsecSA_FullMethodName                = "/bpfrx.v1.BpfrxService/GetIPsecSA"
	BpfrxService_GetNATPoolStats_FullMethodName           = "/bpfrx.v1.BpfrxService/GetNATPoolStats"
	BpfrxService_GetNATRuleStats_FullMethodName           = "/bpfrx.v1.BpfrxService/GetNATRuleStats"
	BpfrxService_GetVRRPStatus_FullMethodName             = "/bpfrx.v1.BpfrxService/GetVRRPStatus"
	BpfrxService_MatchPolicies_FullMethodName             = "/bpfrx.v1.BpfrxService/MatchPolicies"
	BpfrxService_Ping_FullMethodName                      = "/bpfrx.v1.BpfrxService/Ping"
	BpfrxService_Traceroute_FullMethodName                = "/bpfrx.v1.BpfrxService/Traceroute"
	BpfrxService_ClearSessions_FullMethodName             = "/bpfrx.v1.BpfrxService/ClearSessions"
	BpfrxService_ClearCounters_FullMethodName             = "/bpfrx.v1.BpfrxService/ClearCounters"
	BpfrxService_ClearDHCPClientIdentifier_FullMethodName = "/bpfrx.v1.BpfrxService/ClearDHCPClientIdentifier"
	BpfrxService_Complete_FullMethodName                  = "/bpfrx.v1.BpfrxService/Complete"
)

// BpfrxServiceClient is the client API for BpfrxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BpfrxService provides gRPC access to the bpfrx firewall daemon.
type BpfrxServiceClient interface {
	// Config lifecycle
	EnterConfigure(ctx context.Context, in *EnterConfigureRequest, opts ...grpc.CallOption) (*EnterConfigureResponse, error)
	ExitConfigure(ctx context.Context, in *ExitConfigureRequest, opts ...grpc.CallOption) (*ExitConfigureResponse, error)
	GetConfigModeStatus(ctx context.Context, in *GetConfigModeStatusRequest, opts ...grpc.CallOption) (*GetConfigModeStatusResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	CommitCheck(ctx context.Context, in *CommitCheckRequest, opts ...grpc.CallOption) (*CommitCheckResponse, error)
	CommitConfirmed(ctx context.Context, in *CommitConfirmedRequest, opts ...grpc.CallOption) (*CommitConfirmedResponse, error)
	ConfirmCommit(ctx context.Context, in *ConfirmCommitRequest, opts ...grpc.CallOption) (*ConfirmCommitResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	ShowConfig(ctx context.Context, in *ShowConfigRequest, opts ...grpc.CallOption) (*ShowConfigResponse, error)
	ShowCompare(ctx context.Context, in *ShowCompareRequest, opts ...grpc.CallOption) (*ShowCompareResponse, error)
	ShowRollback(ctx context.Context, in *ShowRollbackRequest, opts ...grpc.CallOption) (*ShowRollbackResponse, error)
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
	// Operational show RPCs
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GetGlobalStatsResponse, error)
	GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesResponse, error)
	GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error)
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
	GetSessionSummary(ctx context.Context, in *GetSessionSummaryRequest, opts ...grpc.CallOption) (*GetSessionSummaryResponse, error)
	GetNATSource(ctx context.Context, in *GetNATSourceRequest, opts ...grpc.CallOption) (*GetNATSourceResponse, error)
	GetNATDestination(ctx context.Context, in *GetNATDestinationRequest, opts ...grpc.CallOption) (*GetNATDestinationResponse, error)
	GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	GetInterfaces(ctx context.Context, in *GetInterfacesRequest, opts ...grpc.CallOption) (*GetInterfacesResponse, error)
	ShowInterfacesDetail(ctx context.Context, in *ShowInterfacesDetailRequest, opts ...grpc.CallOption) (*ShowInterfacesDetailResponse, error)
	GetDHCPLeases(ctx context.Context, in *GetDHCPLeasesRequest, opts ...grpc.CallOption) (*GetDHCPLeasesResponse, error)
	GetDHCPClientIdentifiers(ctx context.Context, in *GetDHCPClientIdentifiersRequest, opts ...grpc.CallOption) (*GetDHCPClientIdentifiersResponse, error)
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	GetOSPFStatus(ctx context.Context, in *GetOSPFStatusRequest, opts ...grpc.CallOption) (*GetOSPFStatusResponse, error)
	GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error)
	GetIPsecSA(ctx context.Context, in *GetIPsecSARequest, opts ...grpc.CallOption) (*GetIPsecSAResponse, error)
	GetNATPoolStats(ctx context.Context, in *GetNATPoolStatsRequest, opts ...grpc.CallOption) (*GetNATPoolStatsResponse, error)
	GetNATRuleStats(ctx context.Context, in *GetNATRuleStatsRequest, opts ...grpc.CallOption) (*GetNATRuleStatsResponse, error)
	GetVRRPStatus(ctx context.Context, in *GetVRRPStatusRequest, opts ...grpc.CallOption) (*GetVRRPStatusResponse, error)
	MatchPolicies(ctx context.Context, in *MatchPoliciesRequest, opts ...grpc.CallOption) (*MatchPoliciesResponse, error)
	// Diagnostics
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (*TracerouteResponse, error)
	// Mutations
	ClearSessions(ctx context.Context, in *ClearSessionsRequest, opts ...grpc.CallOption) (*ClearSessionsResponse, error)
	ClearCounters(ctx context.Context, in *ClearCountersRequest, opts ...grpc.CallOption) (*ClearCountersResponse, error)
	ClearDHCPClientIdentifier(ctx context.Context, in *ClearDHCPClientIdentifierRequest, opts ...grpc.CallOption) (*ClearDHCPClientIdentifierResponse, error)
	// Tab completion
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
}

type bpfrxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBpfrxServiceClient(cc grpc.ClientConnInterface) BpfrxServiceClient {
	return &bpfrxServiceClient{cc}
}

func (c *bpfrxServiceClient) EnterConfigure(ctx context.Context, in *EnterConfigureRequest, opts ...grpc.CallOption) (*EnterConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterConfigureResponse)
	err := c.cc.Invoke(ctx, BpfrxService_EnterConfigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ExitConfigure(ctx context.Context, in *ExitConfigureRequest, opts ...grpc.CallOption) (*ExitConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitConfigureResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ExitConfigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetConfigModeStatus(ctx context.Context, in *GetConfigModeStatusRequest, opts ...grpc.CallOption) (*GetConfigModeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigModeStatusResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetConfigModeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) CommitCheck(ctx context.Context, in *CommitCheckRequest, opts ...grpc.CallOption) (*CommitCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitCheckResponse)
	err := c.cc.Invoke(ctx, BpfrxService_CommitCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) CommitConfirmed(ctx context.Context, in *CommitConfirmedRequest, opts ...grpc.CallOption) (*CommitConfirmedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitConfirmedResponse)
	err := c.cc.Invoke(ctx, BpfrxService_CommitConfirmed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ConfirmCommit(ctx context.Context, in *ConfirmCommitRequest, opts ...grpc.CallOption) (*ConfirmCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCommitResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ConfirmCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ShowConfig(ctx context.Context, in *ShowConfigRequest, opts ...grpc.CallOption) (*ShowConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowConfigResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ShowConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ShowCompare(ctx context.Context, in *ShowCompareRequest, opts ...grpc.CallOption) (*ShowCompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowCompareResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ShowCompare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ShowRollback(ctx context.Context, in *ShowRollbackRequest, opts ...grpc.CallOption) (*ShowRollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowRollbackResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ShowRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetGlobalStats(ctx context.Context, in *GetGlobalStatsRequest, opts ...grpc.CallOption) (*GetGlobalStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalStatsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetGlobalStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZonesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoliciesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetSessionSummary(ctx context.Context, in *GetSessionSummaryRequest, opts ...grpc.CallOption) (*GetSessionSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionSummaryResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetSessionSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetNATSource(ctx context.Context, in *GetNATSourceRequest, opts ...grpc.CallOption) (*GetNATSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNATSourceResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetNATSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetNATDestination(ctx context.Context, in *GetNATDestinationRequest, opts ...grpc.CallOption) (*GetNATDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNATDestinationResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetNATDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScreenResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetInterfaces(ctx context.Context, in *GetInterfacesRequest, opts ...grpc.CallOption) (*GetInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfacesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ShowInterfacesDetail(ctx context.Context, in *ShowInterfacesDetailRequest, opts ...grpc.CallOption) (*ShowInterfacesDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowInterfacesDetailResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ShowInterfacesDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetDHCPLeases(ctx context.Context, in *GetDHCPLeasesRequest, opts ...grpc.CallOption) (*GetDHCPLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDHCPLeasesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetDHCPLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetDHCPClientIdentifiers(ctx context.Context, in *GetDHCPClientIdentifiersRequest, opts ...grpc.CallOption) (*GetDHCPClientIdentifiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDHCPClientIdentifiersResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetDHCPClientIdentifiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetOSPFStatus(ctx context.Context, in *GetOSPFStatusRequest, opts ...grpc.CallOption) (*GetOSPFStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOSPFStatusResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetOSPFStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetBGPStatus(ctx context.Context, in *GetBGPStatusRequest, opts ...grpc.CallOption) (*GetBGPStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBGPStatusResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetBGPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetIPsecSA(ctx context.Context, in *GetIPsecSARequest, opts ...grpc.CallOption) (*GetIPsecSAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPsecSAResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetIPsecSA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetNATPoolStats(ctx context.Context, in *GetNATPoolStatsRequest, opts ...grpc.CallOption) (*GetNATPoolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNATPoolStatsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetNATPoolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetNATRuleStats(ctx context.Context, in *GetNATRuleStatsRequest, opts ...grpc.CallOption) (*GetNATRuleStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNATRuleStatsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetNATRuleStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) GetVRRPStatus(ctx context.Context, in *GetVRRPStatusRequest, opts ...grpc.CallOption) (*GetVRRPStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVRRPStatusResponse)
	err := c.cc.Invoke(ctx, BpfrxService_GetVRRPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) MatchPolicies(ctx context.Context, in *MatchPoliciesRequest, opts ...grpc.CallOption) (*MatchPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchPoliciesResponse)
	err := c.cc.Invoke(ctx, BpfrxService_MatchPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (*TracerouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TracerouteResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Traceroute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ClearSessions(ctx context.Context, in *ClearSessionsRequest, opts ...grpc.CallOption) (*ClearSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSessionsResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ClearSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ClearCounters(ctx context.Context, in *ClearCountersRequest, opts ...grpc.CallOption) (*ClearCountersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCountersResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ClearCounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) ClearDHCPClientIdentifier(ctx context.Context, in *ClearDHCPClientIdentifierRequest, opts ...grpc.CallOption) (*ClearDHCPClientIdentifierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearDHCPClientIdentifierResponse)
	err := c.cc.Invoke(ctx, BpfrxService_ClearDHCPClientIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfrxServiceClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, BpfrxService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BpfrxServiceServer is the server API for BpfrxService service.
// All implementations must embed UnimplementedBpfrxServiceServer
// for forward compatibility.
//
// BpfrxService provides gRPC access to the bpfrx firewall daemon.
type BpfrxServiceServer interface {
	// Config lifecycle
	EnterConfigure(context.Context, *EnterConfigureRequest) (*EnterConfigureResponse, error)
	ExitConfigure(context.Context, *ExitConfigureRequest) (*ExitConfigureResponse, error)
	GetConfigModeStatus(context.Context, *GetConfigModeStatusRequest) (*GetConfigModeStatusResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	CommitCheck(context.Context, *CommitCheckRequest) (*CommitCheckResponse, error)
	CommitConfirmed(context.Context, *CommitConfirmedRequest) (*CommitConfirmedResponse, error)
	ConfirmCommit(context.Context, *ConfirmCommitRequest) (*ConfirmCommitResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	ShowConfig(context.Context, *ShowConfigRequest) (*ShowConfigResponse, error)
	ShowCompare(context.Context, *ShowCompareRequest) (*ShowCompareResponse, error)
	ShowRollback(context.Context, *ShowRollbackRequest) (*ShowRollbackResponse, error)
	ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	// Operational show RPCs
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GetGlobalStatsResponse, error)
	GetZones(context.Context, *GetZonesRequest) (*GetZonesResponse, error)
	GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error)
	GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error)
	GetSessionSummary(context.Context, *GetSessionSummaryRequest) (*GetSessionSummaryResponse, error)
	GetNATSource(context.Context, *GetNATSourceRequest) (*GetNATSourceResponse, error)
	GetNATDestination(context.Context, *GetNATDestinationRequest) (*GetNATDestinationResponse, error)
	GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	GetInterfaces(context.Context, *GetInterfacesRequest) (*GetInterfacesResponse, error)
	ShowInterfacesDetail(context.Context, *ShowInterfacesDetailRequest) (*ShowInterfacesDetailResponse, error)
	GetDHCPLeases(context.Context, *GetDHCPLeasesRequest) (*GetDHCPLeasesResponse, error)
	GetDHCPClientIdentifiers(context.Context, *GetDHCPClientIdentifiersRequest) (*GetDHCPClientIdentifiersResponse, error)
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	GetOSPFStatus(context.Context, *GetOSPFStatusRequest) (*GetOSPFStatusResponse, error)
	GetBGPStatus(context.Context, *GetBGPStatusRequest) (*GetBGPStatusResponse, error)
	GetIPsecSA(context.Context, *GetIPsecSARequest) (*GetIPsecSAResponse, error)
	GetNATPoolStats(context.Context, *GetNATPoolStatsRequest) (*GetNATPoolStatsResponse, error)
	GetNATRuleStats(context.Context, *GetNATRuleStatsRequest) (*GetNATRuleStatsResponse, error)
	GetVRRPStatus(context.Context, *GetVRRPStatusRequest) (*GetVRRPStatusResponse, error)
	MatchPolicies(context.Context, *MatchPoliciesRequest) (*MatchPoliciesResponse, error)
	// Diagnostics
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Traceroute(context.Context, *TracerouteRequest) (*TracerouteResponse, error)
	// Mutations
	ClearSessions(context.Context, *ClearSessionsRequest) (*ClearSessionsResponse, error)
	ClearCounters(context.Context, *ClearCountersRequest) (*ClearCountersResponse, error)
	ClearDHCPClientIdentifier(context.Context, *ClearDHCPClientIdentifierRequest) (*ClearDHCPClientIdentifierResponse, error)
	// Tab completion
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	mustEmbedUnimplementedBpfrxServiceServer()
}

// UnimplementedBpfrxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBpfrxServiceServer struct{}

func (UnimplementedBpfrxServiceServer) EnterConfigure(context.Context, *EnterConfigureRequest) (*EnterConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnterConfigure not implemented")
}
func (UnimplementedBpfrxServiceServer) ExitConfigure(context.Context, *ExitConfigureRequest) (*ExitConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExitConfigure not implemented")
}
func (UnimplementedBpfrxServiceServer) GetConfigModeStatus(context.Context, *GetConfigModeStatusRequest) (*GetConfigModeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigModeStatus not implemented")
}
func (UnimplementedBpfrxServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedBpfrxServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBpfrxServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedBpfrxServiceServer) CommitCheck(context.Context, *CommitCheckRequest) (*CommitCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitCheck not implemented")
}
func (UnimplementedBpfrxServiceServer) CommitConfirmed(context.Context, *CommitConfirmedRequest) (*CommitConfirmedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitConfirmed not implemented")
}
func (UnimplementedBpfrxServiceServer) ConfirmCommit(context.Context, *ConfirmCommitRequest) (*ConfirmCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCommit not implemented")
}
func (UnimplementedBpfrxServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedBpfrxServiceServer) ShowConfig(context.Context, *ShowConfigRequest) (*ShowConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowConfig not implemented")
}
func (UnimplementedBpfrxServiceServer) ShowCompare(context.Context, *ShowCompareRequest) (*ShowCompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowCompare not implemented")
}
func (UnimplementedBpfrxServiceServer) ShowRollback(context.Context, *ShowRollbackRequest) (*ShowRollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowRollback not implemented")
}
func (UnimplementedBpfrxServiceServer) ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedBpfrxServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBpfrxServiceServer) GetGlobalStats(context.Context, *GetGlobalStatsRequest) (*GetGlobalStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalStats not implemented")
}
func (UnimplementedBpfrxServiceServer) GetZones(context.Context, *GetZonesRequest) (*GetZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZones not implemented")
}
func (UnimplementedBpfrxServiceServer) GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedBpfrxServiceServer) GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedBpfrxServiceServer) GetSessionSummary(context.Context, *GetSessionSummaryRequest) (*GetSessionSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionSummary not implemented")
}
func (UnimplementedBpfrxServiceServer) GetNATSource(context.Context, *GetNATSourceRequest) (*GetNATSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNATSource not implemented")
}
func (UnimplementedBpfrxServiceServer) GetNATDestination(context.Context, *GetNATDestinationRequest) (*GetNATDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNATDestination not implemented")
}
func (UnimplementedBpfrxServiceServer) GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScreen not implemented")
}
func (UnimplementedBpfrxServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedBpfrxServiceServer) GetInterfaces(context.Context, *GetInterfacesRequest) (*GetInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaces not implemented")
}
func (UnimplementedBpfrxServiceServer) ShowInterfacesDetail(context.Context, *ShowInterfacesDetailRequest) (*ShowInterfacesDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowInterfacesDetail not implemented")
}
func (UnimplementedBpfrxServiceServer) GetDHCPLeases(context.Context, *GetDHCPLeasesRequest) (*GetDHCPLeasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDHCPLeases not implemented")
}
func (UnimplementedBpfrxServiceServer) GetDHCPClientIdentifiers(context.Context, *GetDHCPClientIdentifiersRequest) (*GetDHCPClientIdentifiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDHCPClientIdentifiers not implemented")
}
func (UnimplementedBpfrxServiceServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedBpfrxServiceServer) GetOSPFStatus(context.Context, *GetOSPFStatusRequest) (*GetOSPFStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOSPFStatus not implemented")
}
func (UnimplementedBpfrxServiceServer) GetBGPStatus(context.Context, *GetBGPStatusRequest) (*GetBGPStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBGPStatus not implemented")
}
func (UnimplementedBpfrxServiceServer) GetIPsecSA(context.Context, *GetIPsecSARequest) (*GetIPsecSAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPsecSA not implemented")
}
func (UnimplementedBpfrxServiceServer) GetNATPoolStats(context.Context, *GetNATPoolStatsRequest) (*GetNATPoolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNATPoolStats not implemented")
}
func (UnimplementedBpfrxServiceServer) GetNATRuleStats(context.Context, *GetNATRuleStatsRequest) (*GetNATRuleStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNATRuleStats not implemented")
}
func (UnimplementedBpfrxServiceServer) GetVRRPStatus(context.Context, *GetVRRPStatusRequest) (*GetVRRPStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVRRPStatus not implemented")
}
func (UnimplementedBpfrxServiceServer) MatchPolicies(context.Context, *MatchPoliciesRequest) (*MatchPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchPolicies not implemented")
}
func (UnimplementedBpfrxServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBpfrxServiceServer) Traceroute(context.Context, *TracerouteRequest) (*TracerouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Traceroute not implemented")
}
func (UnimplementedBpfrxServiceServer) ClearSessions(context.Context, *ClearSessionsRequest) (*ClearSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearSessions not implemented")
}
func (UnimplementedBpfrxServiceServer) ClearCounters(context.Context, *ClearCountersRequest) (*ClearCountersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearCounters not implemented")
}
func (UnimplementedBpfrxServiceServer) ClearDHCPClientIdentifier(context.Context, *ClearDHCPClientIdentifierRequest) (*ClearDHCPClientIdentifierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearDHCPClientIdentifier not implemented")
}
func (UnimplementedBpfrxServiceServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedBpfrxServiceServer) mustEmbedUnimplementedBpfrxServiceServer() {}
func (UnimplementedBpfrxServiceServer) testEmbeddedByValue()                      {}

// UnsafeBpfrxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BpfrxServiceServer will
// result in compilation errors.
type UnsafeBpfrxServiceServer interface {
	mustEmbedUnimplementedBpfrxServiceServer()
}

func RegisterBpfrxServiceServer(s grpc.ServiceRegistrar, srv BpfrxServiceServer) {
	// If the following call panics, it indicates UnimplementedBpfrxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BpfrxService_ServiceDesc, srv)
}

func _BpfrxService_EnterConfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).EnterConfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_EnterConfigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).EnterConfigure(ctx, req.(*EnterConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ExitConfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ExitConfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ExitConfigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ExitConfigure(ctx, req.(*ExitConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetConfigModeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigModeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetConfigModeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetConfigModeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetConfigModeStatus(ctx, req.(*GetConfigModeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_CommitCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).CommitCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_CommitCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).CommitCheck(ctx, req.(*CommitCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_CommitConfirmed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitConfirmedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).CommitConfirmed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_CommitConfirmed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).CommitConfirmed(ctx, req.(*CommitConfirmedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ConfirmCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ConfirmCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ConfirmCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ConfirmCommit(ctx, req.(*ConfirmCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ShowConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ShowConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ShowConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ShowConfig(ctx, req.(*ShowConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ShowCompare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowCompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ShowCompare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ShowCompare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ShowCompare(ctx, req.(*ShowCompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ShowRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ShowRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ShowRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ShowRollback(ctx, req.(*ShowRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetGlobalStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetGlobalStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetGlobalStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetGlobalStats(ctx, req.(*GetGlobalStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetZones(ctx, req.(*GetZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetPolicies(ctx, req.(*GetPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetSessionSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetSessionSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetSessionSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetSessionSummary(ctx, req.(*GetSessionSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetNATSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNATSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetNATSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetNATSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetNATSource(ctx, req.(*GetNATSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetNATDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNATDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetNATDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetNATDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetNATDestination(ctx, req.(*GetNATDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetScreen(ctx, req.(*GetScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetInterfaces(ctx, req.(*GetInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ShowInterfacesDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowInterfacesDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ShowInterfacesDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ShowInterfacesDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ShowInterfacesDetail(ctx, req.(*ShowInterfacesDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetDHCPLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDHCPLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetDHCPLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetDHCPLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetDHCPLeases(ctx, req.(*GetDHCPLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetDHCPClientIdentifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDHCPClientIdentifiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetDHCPClientIdentifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetDHCPClientIdentifiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetDHCPClientIdentifiers(ctx, req.(*GetDHCPClientIdentifiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetOSPFStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOSPFStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetOSPFStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetOSPFStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetOSPFStatus(ctx, req.(*GetOSPFStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetBGPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBGPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetBGPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetBGPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetBGPStatus(ctx, req.(*GetBGPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetIPsecSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPsecSARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetIPsecSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetIPsecSA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetIPsecSA(ctx, req.(*GetIPsecSARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetNATPoolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNATPoolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetNATPoolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetNATPoolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetNATPoolStats(ctx, req.(*GetNATPoolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetNATRuleStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNATRuleStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetNATRuleStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetNATRuleStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetNATRuleStats(ctx, req.(*GetNATRuleStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_GetVRRPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVRRPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).GetVRRPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_GetVRRPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).GetVRRPStatus(ctx, req.(*GetVRRPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_MatchPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).MatchPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_MatchPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).MatchPolicies(ctx, req.(*MatchPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Traceroute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TracerouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Traceroute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Traceroute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Traceroute(ctx, req.(*TracerouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ClearSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ClearSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ClearSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ClearSessions(ctx, req.(*ClearSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ClearCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ClearCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ClearCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ClearCounters(ctx, req.(*ClearCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_ClearDHCPClientIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearDHCPClientIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).ClearDHCPClientIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_ClearDHCPClientIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).ClearDHCPClientIdentifier(ctx, req.(*ClearDHCPClientIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfrxService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfrxServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfrxService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfrxServiceServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BpfrxService_ServiceDesc is the grpc.ServiceDesc for BpfrxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BpfrxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpfrx.v1.BpfrxService",
	HandlerType: (*BpfrxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnterConfigure",
			Handler:    _BpfrxService_EnterConfigure_Handler,
		},
		{
			MethodName: "ExitConfigure",
			Handler:    _BpfrxService_ExitConfigure_Handler,
		},
		{
			MethodName: "GetConfigModeStatus",
			Handler:    _BpfrxService_GetConfigModeStatus_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _BpfrxService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BpfrxService_Delete_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _BpfrxService_Commit_Handler,
		},
		{
			MethodName: "CommitCheck",
			Handler:    _BpfrxService_CommitCheck_Handler,
		},
		{
			MethodName: "CommitConfirmed",
			Handler:    _BpfrxService_CommitConfirmed_Handler,
		},
		{
			MethodName: "ConfirmCommit",
			Handler:    _BpfrxService_ConfirmCommit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _BpfrxService_Rollback_Handler,
		},
		{
			MethodName: "ShowConfig",
			Handler:    _BpfrxService_ShowConfig_Handler,
		},
		{
			MethodName: "ShowCompare",
			Handler:    _BpfrxService_ShowCompare_Handler,
		},
		{
			MethodName: "ShowRollback",
			Handler:    _BpfrxService_ShowRollback_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _BpfrxService_ListHistory_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BpfrxService_GetStatus_Handler,
		},
		{
			MethodName: "GetGlobalStats",
			Handler:    _BpfrxService_GetGlobalStats_Handler,
		},
		{
			MethodName: "GetZones",
			Handler:    _BpfrxService_GetZones_Handler,
		},
		{
			MethodName: "GetPolicies",
			Handler:    _BpfrxService_GetPolicies_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _BpfrxService_GetSessions_Handler,
		},
		{
			MethodName: "GetSessionSummary",
			Handler:    _BpfrxService_GetSessionSummary_Handler,
		},
		{
			MethodName: "GetNATSource",
			Handler:    _BpfrxService_GetNATSource_Handler,
		},
		{
			MethodName: "GetNATDestination",
			Handler:    _BpfrxService_GetNATDestination_Handler,
		},
		{
			MethodName: "GetScreen",
			Handler:    _BpfrxService_GetScreen_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _BpfrxService_GetEvents_Handler,
		},
		{
			MethodName: "GetInterfaces",
			Handler:    _BpfrxService_GetInterfaces_Handler,
		},
		{
			MethodName: "ShowInterfacesDetail",
			Handler:    _BpfrxService_ShowInterfacesDetail_Handler,
		},
		{
			MethodName: "GetDHCPLeases",
			Handler:    _BpfrxService_GetDHCPLeases_Handler,
		},
		{
			MethodName: "GetDHCPClientIdentifiers",
			Handler:    _BpfrxService_GetDHCPClientIdentifiers_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _BpfrxService_GetRoutes_Handler,
		},
		{
			MethodName: "GetOSPFStatus",
			Handler:    _BpfrxService_GetOSPFStatus_Handler,
		},
		{
			MethodName: "GetBGPStatus",
			Handler:    _BpfrxService_GetBGPStatus_Handler,
		},
		{
			MethodName: "GetIPsecSA",
			Handler:    _BpfrxService_GetIPsecSA_Handler,
		},
		{
			MethodName: "GetNATPoolStats",
			Handler:    _BpfrxService_GetNATPoolStats_Handler,
		},
		{
			MethodName: "GetNATRuleStats",
			Handler:    _BpfrxService_GetNATRuleStats_Handler,
		},
		{
			MethodName: "GetVRRPStatus",
			Handler:    _BpfrxService_GetVRRPStatus_Handler,
		},
		{
			MethodName: "MatchPolicies",
			Handler:    _BpfrxService_MatchPolicies_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BpfrxService_Ping_Handler,
		},
		{
			MethodName: "Traceroute",
			Handler:    _BpfrxService_Traceroute_Handler,
		},
		{
			MethodName: "ClearSessions",
			Handler:    _BpfrxService_ClearSessions_Handler,
		},
		{
			MethodName: "ClearCounters",
			Handler:    _BpfrxService_ClearCounters_Handler,
		},
		{
			MethodName: "ClearDHCPClientIdentifier",
			Handler:    _BpfrxService_ClearDHCPClientIdentifier_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _BpfrxService_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bpfrx.proto",
}
