package daemon

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"golang.org/x/sys/unix"

	"github.com/psaab/xpf/pkg/config"
	"github.com/psaab/xpf/pkg/daemon/system"
	"github.com/psaab/xpf/pkg/dhcp"
)

// isCrossDeviceOrBusy reports whether err is an EXDEV/EBUSY from rename(2)
// onto /etc/resolv.conf — the symptom of /etc/resolv.conf being a bind
// mount (common in CI/containers), where an atomic rename onto the mount
// point is not permitted and an in-place write is the only option.
func isCrossDeviceOrBusy(err error) bool {
	return errors.Is(err, unix.EXDEV) || errors.Is(err, unix.EBUSY)
}

// DNS ownership (#1715)
//
// xpf owns /etc/resolv.conf as a managed plain file. systemd-resolved is
// deterministically disabled + masked; the legacy bpfrx.conf drop-in is
// removed. A single reconcileDNS is the only writer of /etc/resolv.conf,
// merging static `system name-server` config with DHCP-learned
// nameservers from every live lease (v4 + v6). It runs at startup, on
// every config apply, and on every DHCP address change.
//
// This replaces the prior three-owner straddle (applySystemDNS wrote a
// resolved drop-in + restarted resolved; applyDNSService disabled
// resolved two lines later — a self-inflicted apply-order race that left
// /etc/resolv.conf a dangling symlink; the DHCP installDNS path wrote
// the file through that symlink and failed silently). See
// docs/dns-ownership.md.

const (
	resolvConfPath = "/etc/resolv.conf"
	// legacyResolvedDropin is the stale pre-rename drop-in
	// (`# Generated by bpfrxd`). Current code only writes/removes
	// xpf.conf; nothing ever removed bpfrx.conf. Inert while resolved is
	// off, but it would double-apply DNS= if resolved were ever the
	// owner, so the reconciler removes it.
	legacyResolvedDropin = "/etc/systemd/resolved.conf.d/bpfrx.conf"
	// xpfResolvedDropin is the drop-in the old applySystemDNS wrote.
	// With xpf owning resolv.conf directly and resolved masked, it is
	// dead; remove it so a future operator unmask of resolved does not
	// resurrect a second owner.
	xpfResolvedDropin = "/etc/systemd/resolved.conf.d/xpf.conf"
)

// dnsReconciler performs the filesystem + systemd side of DNS ownership.
// Paths and systemd ops are fields so unit tests can target a tempdir
// and stub the service calls; production uses newDNSReconciler().
type dnsReconciler struct {
	resolvConfPath       string
	legacyResolvedDropin string
	xpfResolvedDropin    string
	// disableMaskResolved disables + masks systemd-resolved. Returns an
	// error on failure so the reconciler does NOT assume resolved is off
	// (a still-running resolved would be a second owner). Stubbed in
	// tests.
	disableMaskResolved func() error
}

func newDNSReconciler() *dnsReconciler {
	return &dnsReconciler{
		resolvConfPath:       resolvConfPath,
		legacyResolvedDropin: legacyResolvedDropin,
		xpfResolvedDropin:    xpfResolvedDropin,
		disableMaskResolved:  disableMaskResolved,
	}
}

// mergeDNSInput builds the renderer input from static config plus the
// DHCP leases the manager currently holds. Precedence: static
// `system name-server` first, then DHCPv4, then DHCPv6, de-duplicated
// (static is authoritative; DHCP augments, never overrides).
//
// Lease lifecycle note: dhcp.Leases() reflects the manager's held leases.
// A lease is dropped (and thus stops contributing DNS) when its client is
// stopped or the interface is deconfigured; on a transient
// renewal/rebind failure the manager intentionally keeps the last lease
// and keeps using its address until a fresh DORA succeeds, so its DNS is
// retained too — matching the address it is still bound to (a firewall
// must not blackhole its own management resolver mid-renewal). DNS only
// truly clears when no held lease and no static name-server remain.
// domain-name / domain-search come from
// static config only (DHCP domain options are not consumed here).
func mergeDNSInput(cfg *config.Config, leases []*dhcp.Lease) system.ResolvedDropinInput {
	seen := make(map[string]struct{})
	var servers []string
	add := func(s string) {
		if s == "" {
			return
		}
		if _, dup := seen[s]; dup {
			return
		}
		seen[s] = struct{}{}
		servers = append(servers, s)
	}

	if cfg != nil {
		for _, ns := range cfg.System.NameServers {
			add(ns)
		}
	}
	// DHCPv4 leases first, then DHCPv6. Within a family, leases are
	// sorted by interface name so the merge is deterministic regardless
	// of dhcp.Leases() map-iteration order — otherwise resolver priority
	// (and the byte-for-byte idempotence compare) would flap when two
	// interfaces in the same family both learn DNS.
	sorted := make([]*dhcp.Lease, 0, len(leases))
	for _, l := range leases {
		if l != nil {
			sorted = append(sorted, l)
		}
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Interface < sorted[j].Interface
	})
	for _, fam := range []dhcp.AddressFamily{dhcp.AFInet, dhcp.AFInet6} {
		for _, l := range sorted {
			if l.Family != fam {
				continue
			}
			for _, ip := range l.DNS {
				add(ip.String())
			}
		}
	}

	in := system.ResolvedDropinInput{NameServers: servers}
	if cfg != nil {
		in.DomainName = cfg.System.DomainName
		in.DomainSearch = cfg.System.DomainSearch
	}
	return in
}

// reconcile renders the merged input and reconciles /etc/resolv.conf as a
// managed plain file, removes stale resolved drop-ins, and disables +
// masks systemd-resolved.
//
// bootEmptyRepairOnly selects the §5b.4 boot policy: when true (first
// startup apply, before any DHCP lease) and there are NO nameservers to
// install (a search-only render is not a usable resolver), an existing
// non-dangling regular /etc/resolv.conf is left untouched — only a
// dangling / symlinked / missing file is repaired. The guard keys off
// the nameserver set (not in.Empty()) so a config carrying only
// domain-name/domain-search with no static name-server and no lease does
// not blank a good resolver file at boot. When false (an explicit
// runtime commit or a DHCP change), a no-nameserver render is a
// declarative "clear DNS" and the managed file is written so removing
// all name-servers / expiring the last lease actually clears the
// resolver instead of leaking stale servers.
func (r *dnsReconciler) reconcile(in system.ResolvedDropinInput, bootEmptyRepairOnly bool) {
	// Always converge resolved off + remove stale drop-ins, regardless of
	// whether resolv.conf needs rewriting, so a previously-installed
	// drop-in / running resolved is cleaned up even on an idempotent pass.
	if err := r.disableMaskResolved(); err != nil {
		// Do NOT proceed assuming resolved is off — it would be a second
		// owner. Still own resolv.conf (a static file wins over an
		// inactive stub), but surface the failure loudly.
		slog.Warn("DNS: failed to disable+mask systemd-resolved; it may remain a second resolver owner", "err", err)
	}
	for _, p := range []string{r.legacyResolvedDropin, r.xpfResolvedDropin} {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			slog.Warn("DNS: failed to remove stale resolved drop-in", "path", p, "err", err)
		}
	}

	content := system.RenderResolvConf(in)

	// Inspect the current target without following symlinks.
	fi, lerr := os.Lstat(r.resolvConfPath)
	isSymlink := lerr == nil && fi.Mode()&os.ModeSymlink != 0
	missing := os.IsNotExist(lerr)

	// Boot empty-merge policy: no nameservers to install and a good
	// regular file already exists → repair only a bad (symlink/missing)
	// target, never clobber a good file. A symlink (e.g. the dangling
	// stub) or a missing file IS repaired below by writing the managed
	// file. Keyed on the nameserver set, not in.Empty(), so a
	// domain-name/domain-search-only config does not blank a good file.
	if len(in.NameServers) == 0 && bootEmptyRepairOnly && !isSymlink && !missing && lerr == nil {
		return
	}

	// Idempotence: if the target is already a regular file with identical
	// content, skip the rewrite (and the restart churn it would imply).
	if !isSymlink && lerr == nil {
		if cur, err := os.ReadFile(r.resolvConfPath); err == nil && string(cur) == content {
			return
		}
	}

	if err := r.atomicWrite(content); err != nil {
		slog.Warn("DNS: failed to write managed /etc/resolv.conf", "path", r.resolvConfPath, "err", err)
		return
	}
	slog.Info("DNS: reconciled managed /etc/resolv.conf",
		"servers", in.NameServers, "domain", in.DomainName, "search", in.DomainSearch,
		"replaced_symlink", isSymlink)
}

// atomicWrite replaces resolvConfPath with content. It writes a temp file
// in the same directory and renames it over the target. rename(2)
// atomically replaces a symlink target WITHOUT following it, so a
// dangling/stub symlink is swapped for a real file with no ENOENT window
// and no need to os.Remove the symlink first.
//
// On EXDEV/EBUSY (rename across a bind mount, common in CI/containers
// where /etc/resolv.conf is bind-mounted) it falls back to truncating
// and writing the target in place.
func (r *dnsReconciler) atomicWrite(content string) error {
	dir := filepath.Dir(r.resolvConfPath)
	tmp, err := os.CreateTemp(dir, ".resolv.conf.xpf-*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once renamed away
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, r.resolvConfPath); err != nil {
		if isCrossDeviceOrBusy(err) {
			// Bind-mount fallback: write through to the target in place.
			slog.Warn("DNS: rename onto /etc/resolv.conf failed (likely bind mount); writing in place", "err", err)
			if werr := os.WriteFile(r.resolvConfPath, []byte(content), 0644); werr != nil {
				return fmt.Errorf("in-place write fallback: %w", werr)
			}
			return nil
		}
		return fmt.Errorf("rename onto target: %w", err)
	}
	return nil
}

// disableMaskResolved disables + masks systemd-resolved so neither the
// service nor its socket-activation units (varlink/monitor sockets) can
// re-create the /run/systemd/resolve stub that the base-image symlink
// points at. Masking is sticky across reboots; the unmask path for a
// future resolved-owner mode is documented in docs/dns-ownership.md.
//
// It is idempotent and quiet:
//   - On a systemd-less host (no /run/systemd/system — containers/CI) it
//     is a no-op success; there is no resolved to fight.
//   - When the unit is already `masked` it returns success without
//     re-running systemctl, since `disable --now` on a masked unit fails
//     and would otherwise spam a false "second owner" warning on every
//     commit / DHCP change. Reaching the desired end-state (masked) is
//     the success condition, not a fresh transition.
func disableMaskResolved() error {
	// No systemd → nothing to disable/mask. /run/systemd/system is the
	// canonical "booted with systemd" probe (sd_booted(3)).
	if _, err := os.Stat("/run/systemd/system"); err != nil {
		return nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Already masked? Then we are at the desired end-state — do nothing.
	// `systemctl is-enabled` prints `masked` (exit non-zero) for a masked
	// unit; key off the stdout token, not the exit code.
	out, _ := exec.CommandContext(ctx, "systemctl", "is-enabled", "systemd-resolved.service").CombinedOutput()
	if strings.TrimSpace(string(out)) == "masked" {
		return nil
	}

	if out, err := exec.CommandContext(ctx, "systemctl", "disable", "--now", "systemd-resolved.service").CombinedOutput(); err != nil {
		return fmt.Errorf("disable --now systemd-resolved: %w (%s)", err, string(out))
	}
	if out, err := exec.CommandContext(ctx, "systemctl", "mask", "systemd-resolved.service").CombinedOutput(); err != nil {
		return fmt.Errorf("mask systemd-resolved: %w (%s)", err, string(out))
	}
	return nil
}

// reconcileDNSLocked renders + reconciles DNS. It MUST be called with
// d.applySem held (it is invoked from applyConfigLocked). It must NOT
// re-acquire applySem (deadlock) — i.e. it must not call applyConfig or
// reconcileDNSFromDHCP.
//
// bootEmptyRepairOnly is set by the early-boot apply (before DHCP clients
// start) so an empty merge does not blank a pre-existing good file; a
// later commit / DHCP change passes false so clearing DNS truly clears
// the file.
func (d *Daemon) reconcileDNSLocked(cfg *config.Config, bootEmptyRepairOnly bool) {
	var leases []*dhcp.Lease
	if d.dhcp != nil {
		leases = d.dhcp.Leases()
	}
	in := mergeDNSInput(cfg, leases)
	newDNSReconciler().reconcile(in, bootEmptyRepairOnly)
}

// reconcileDNSFromDHCP is the DHCP-callback entry point. It acquires
// applySem once, reads the active config, and reconciles DNS with the
// current lease set. This is the path that fixes the fw0 class: a
// management-only interface (fxp0) DHCP change reaches DNS reconcile even
// though it does not trigger a dataplane recompile.
//
// It passes bootEmptyRepairOnly=false: a DHCP change is a live event, and
// if it ever produces an empty merge (last lease expired, no static
// name-server) that is a real "clear DNS".
func (d *Daemon) reconcileDNSFromDHCP() {
	if err := d.applySem.Acquire(context.Background(), 1); err != nil {
		slog.Warn("DNS: failed to acquire apply lock for DHCP reconcile", "err", err)
		return
	}
	defer d.applySem.Release(1)
	cfg := d.store.ActiveConfig()
	d.reconcileDNSLocked(cfg, false)
}
