// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfrxXdpScreenAddrMembershipKey struct {
	_         structs.HostLayout
	Ip        uint32
	AddressId uint32
}

type bpfrxXdpScreenAddrValue struct {
	_         structs.HostLayout
	AddressId uint32
}

type bpfrxXdpScreenAppKey struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      uint8
	DstPort  uint16
}

type bpfrxXdpScreenAppValue struct {
	_           structs.HostLayout
	AppId       uint32
	AlgType     uint8
	Pad         uint8
	Timeout     uint16
	SrcPortLow  uint16
	SrcPortHigh uint16
}

type bpfrxXdpScreenBpfDevmapVal struct {
	_       structs.HostLayout
	Ifindex uint32
	BpfProg struct {
		_  structs.HostLayout
		Fd int32
	}
}

type bpfrxXdpScreenCounterValue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type bpfrxXdpScreenCpumapVal struct {
	_         structs.HostLayout
	Qsize     uint32
	BpfProgFd uint32
}

type bpfrxXdpScreenDnatKey struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      [3]uint8
	DstIp    uint32
	DstPort  uint16
	Pad2     uint16
}

type bpfrxXdpScreenDnatKeyV6 struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      [3]uint8
	DstIp    [16]uint8
	DstPort  uint16
	Pad2     uint16
}

type bpfrxXdpScreenDnatValue struct {
	_          structs.HostLayout
	NewDstIp   uint32
	NewDstPort uint16
	Flags      uint8
	Pad        uint8
}

type bpfrxXdpScreenDnatValueV6 struct {
	_          structs.HostLayout
	NewDstIp   [16]uint8
	NewDstPort uint16
	Flags      uint8
	Pad        uint8
}

type bpfrxXdpScreenFilterConfig struct {
	_         structs.HostLayout
	NumRules  uint32
	RuleStart uint32
}

type bpfrxXdpScreenFilterRule struct {
	_            structs.HostLayout
	MatchFlags   uint16
	Dscp         uint8
	Protocol     uint8
	Action       uint8
	IcmpType     uint8
	IcmpCode     uint8
	Family       uint8
	DstPort      uint16
	SrcPort      uint16
	DstPortHi    uint16
	SrcPortHi    uint16
	DscpRewrite  uint8
	LogFlag      uint8
	TcpFlags     uint8
	IsFragment   uint8
	SrcAddr      [16]uint8
	SrcMask      [16]uint8
	DstAddr      [16]uint8
	DstMask      [16]uint8
	RoutingTable uint32
	PolicerId    uint8
	FlexOffset   uint8
	FlexLength   uint8
	PadRule      uint8
	FlexValue    uint32
	FlexMask     uint32
}

type bpfrxXdpScreenFloodState struct {
	_           structs.HostLayout
	SynCount    uint64
	IcmpCount   uint64
	UdpCount    uint64
	WindowStart uint64
}

type bpfrxXdpScreenFlowConfig struct {
	_                 structs.HostLayout
	TcpMssIpsec       uint16
	TcpMssGreIn       uint16
	TcpMssGreOut      uint16
	AllowDnsReply     uint8
	AllowEmbeddedIcmp uint8
	GreAccel          uint8
	AlgFlags          uint8
	Lo0FilterV4       uint16
	Lo0FilterV6       uint16
}

type bpfrxXdpScreenIfaceCounterValue struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
}

type bpfrxXdpScreenIfaceFilterKey struct {
	_         structs.HostLayout
	Ifindex   uint32
	VlanId    uint16
	Family    uint8
	Direction uint8
}

type bpfrxXdpScreenIfaceZoneKey struct {
	_       structs.HostLayout
	Ifindex uint32
	VlanId  uint16
	Pad     uint16
}

type bpfrxXdpScreenIfaceZoneValue struct {
	_            structs.HostLayout
	ZoneId       uint16
	Pad          uint16
	RoutingTable uint32
}

type bpfrxXdpScreenLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type bpfrxXdpScreenLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type bpfrxXdpScreenMirrorConfig struct {
	_             structs.HostLayout
	MirrorIfindex uint32
	Rate          uint32
}

type bpfrxXdpScreenNat64Config struct {
	_          structs.HostLayout
	Prefix     [3]uint32
	SnatPoolId uint8
	Pad        [3]uint8
}

type bpfrxXdpScreenNat64PrefixKey struct {
	_      structs.HostLayout
	Prefix [3]uint32
}

type bpfrxXdpScreenNat64StateKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfrxXdpScreenNat64StateValue struct {
	_           structs.HostLayout
	OrigSrcV6   [16]uint8
	OrigDstV6   [16]uint8
	OrigSrcPort uint16
	OrigDstPort uint16
	Nat64Idx    uint32
}

type bpfrxXdpScreenPktMeta struct {
	_     structs.HostLayout
	SrcIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	DstIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	SrcPort        uint16
	DstPort        uint16
	Protocol       uint8
	TcpFlags       uint8
	IpTtl          uint8
	AddrFamily     uint8
	Dscp           uint8
	CsumPartial    uint8
	MetaFlags      uint8
	EmbeddedProto  uint8
	IcmpId         uint16
	IcmpType       uint8
	IcmpCode       uint8
	TcpSeq         uint32
	TcpAckSeq      uint32
	L3Offset       uint16
	L4Offset       uint16
	PayloadOffset  uint16
	PktLen         uint16
	IngressZone    uint16
	EgressZone     uint16
	IngressIfindex uint32
	IngressVlanId  uint16
	EgressVlanId   uint16
	Direction      uint8
	IsFragment     uint8
	CtState        uint8
	CtDirection    uint8
	PolicyId       uint32
	NatSrcIp       struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	NatDstIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	NatSrcPort    uint16
	NatDstPort    uint16
	NatFlags      uint32
	FwdIfindex    uint32
	FwdDmac       [6]uint8
	FwdSmac       [6]uint8
	RoutingTable  uint32
	DscpRewrite   uint8
	PadMeta       uint8
	AppTimeout    uint16
	MirrorIfindex uint32
	MirrorRate    uint32
}

type bpfrxXdpScreenPolicerConfig struct {
	_            structs.HostLayout
	RateBytesSec uint64
	BurstBytes   uint64
	Action       uint8
	ColorMode    uint8
	Pad          [6]uint8
	PeakRate     uint64
	PeakBurst    uint64
}

type bpfrxXdpScreenPolicerState struct {
	_            structs.HostLayout
	Tokens       uint64
	LastRefillNs uint64
	PeakTokens   uint64
	PadState     uint64
}

type bpfrxXdpScreenPolicyRule struct {
	_           structs.HostLayout
	RuleId      uint32
	PolicySetId uint32
	Sequence    uint16
	Action      uint8
	Log         uint8
	SrcAddrId   uint32
	DstAddrId   uint32
	DstPortLow  uint16
	DstPortHigh uint16
	Protocol    uint8
	Active      uint8
	Pad         [2]uint8
	AppId       uint32
	NatRuleId   uint32
	CounterId   uint32
}

type bpfrxXdpScreenPolicySet struct {
	_             structs.HostLayout
	PolicySetId   uint32
	NumRules      uint16
	DefaultAction uint16
}

type bpfrxXdpScreenScanTrackKey struct {
	_      structs.HostLayout
	SrcIp  uint32
	ZoneId uint16
	Pad    uint16
}

type bpfrxXdpScreenScanTrackValue struct {
	_           structs.HostLayout
	Count       uint32
	WindowStart uint32
}

type bpfrxXdpScreenScreenConfig struct {
	_                 structs.HostLayout
	Flags             uint32
	SynFloodThresh    uint32
	IcmpFloodThresh   uint32
	UdpFloodThresh    uint32
	SynFloodSrcThresh uint32
	SynFloodDstThresh uint32
	SynFloodTimeout   uint32
	PortScanThresh    uint32
	IpSweepThresh     uint32
}

type bpfrxXdpScreenSessionKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfrxXdpScreenSessionKeyV6 struct {
	_        structs.HostLayout
	SrcIp    [16]uint8
	DstIp    [16]uint8
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfrxXdpScreenSessionValue struct {
	_           structs.HostLayout
	State       uint8
	Flags       uint8
	TcpState    uint8
	IsReverse   uint8
	_           [4]byte
	Created     uint64
	LastSeen    uint64
	Timeout     uint32
	PolicyId    uint32
	IngressZone uint16
	EgressZone  uint16
	NatSrcIp    uint32
	NatDstIp    uint32
	NatSrcPort  uint16
	NatDstPort  uint16
	FwdPackets  uint64
	FwdBytes    uint64
	RevPackets  uint64
	RevBytes    uint64
	ReverseKey  bpfrxXdpScreenSessionKey
	AlgType     uint8
	LogFlags    uint8
	Pad         [2]uint8
	FibIfindex  uint32
	FibVlanId   uint16
	FibDmac     [6]uint8
	FibSmac     [6]uint8
	FibGen      uint16
}

type bpfrxXdpScreenSessionValueV6 struct {
	_           structs.HostLayout
	State       uint8
	Flags       uint8
	TcpState    uint8
	IsReverse   uint8
	_           [4]byte
	Created     uint64
	LastSeen    uint64
	Timeout     uint32
	PolicyId    uint32
	IngressZone uint16
	EgressZone  uint16
	NatSrcIp    [16]uint8
	NatDstIp    [16]uint8
	NatSrcPort  uint16
	NatDstPort  uint16
	FwdPackets  uint64
	FwdBytes    uint64
	RevPackets  uint64
	RevBytes    uint64
	ReverseKey  bpfrxXdpScreenSessionKeyV6
	AlgType     uint8
	LogFlags    uint8
	Pad         [2]uint8
	FibIfindex  uint32
	FibVlanId   uint16
	FibDmac     [6]uint8
	FibSmac     [6]uint8
	FibGen      uint16
}

type bpfrxXdpScreenSnatKey struct {
	_        structs.HostLayout
	FromZone uint16
	ToZone   uint16
	RuleIdx  uint16
	Pad      uint16
}

type bpfrxXdpScreenSnatValue struct {
	_         structs.HostLayout
	SnatIp    uint32
	SrcAddrId uint32
	DstAddrId uint32
	Mode      uint8
	Pad       uint8
	CounterId uint16
}

type bpfrxXdpScreenSnatValueV6 struct {
	_         structs.HostLayout
	SnatIp    [16]uint8
	SrcAddrId uint32
	DstAddrId uint32
	Mode      uint8
	Pad       uint8
	CounterId uint16
}

type bpfrxXdpScreenStaticNatKeyV4 struct {
	_         structs.HostLayout
	Ip        uint32
	Direction uint8
	Pad       [3]uint8
}

type bpfrxXdpScreenStaticNatKeyV6 struct {
	_         structs.HostLayout
	Ip        [16]uint8
	Direction uint8
	Pad       [3]uint8
}

type bpfrxXdpScreenStaticNatValueV6 struct {
	_  structs.HostLayout
	Ip [16]uint8
}

type bpfrxXdpScreenVlanIfaceInfo struct {
	_             structs.HostLayout
	ParentIfindex uint32
	VlanId        uint16
	Pad           uint16
}

type bpfrxXdpScreenZoneConfig struct {
	_                structs.HostLayout
	ZoneId           uint16
	ScreenProfileId  uint16
	HostInboundFlags uint32
	TcpRst           uint8
	Pad              [3]uint8
}

type bpfrxXdpScreenZonePairKey struct {
	_        structs.HostLayout
	FromZone uint16
	ToZone   uint16
}

// loadBpfrxXdpScreen returns the embedded CollectionSpec for bpfrxXdpScreen.
func loadBpfrxXdpScreen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfrxXdpScreenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfrxXdpScreen: %w", err)
	}

	return spec, err
}

// loadBpfrxXdpScreenObjects loads bpfrxXdpScreen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfrxXdpScreenObjects
//	*bpfrxXdpScreenPrograms
//	*bpfrxXdpScreenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfrxXdpScreenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfrxXdpScreen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfrxXdpScreenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxXdpScreenSpecs struct {
	bpfrxXdpScreenProgramSpecs
	bpfrxXdpScreenMapSpecs
	bpfrxXdpScreenVariableSpecs
}

// bpfrxXdpScreenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxXdpScreenProgramSpecs struct {
	XdpScreenProg *ebpf.ProgramSpec `ebpf:"xdp_screen_prog"`
}

// bpfrxXdpScreenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxXdpScreenMapSpecs struct {
	AddressBookV4     *ebpf.MapSpec `ebpf:"address_book_v4"`
	AddressBookV6     *ebpf.MapSpec `ebpf:"address_book_v6"`
	AddressMembership *ebpf.MapSpec `ebpf:"address_membership"`
	Applications      *ebpf.MapSpec `ebpf:"applications"`
	CpuMap            *ebpf.MapSpec `ebpf:"cpu_map"`
	CpumapAvailable   *ebpf.MapSpec `ebpf:"cpumap_available"`
	DefaultPolicy     *ebpf.MapSpec `ebpf:"default_policy"`
	DnatTable         *ebpf.MapSpec `ebpf:"dnat_table"`
	DnatTableV6       *ebpf.MapSpec `ebpf:"dnat_table_v6"`
	Events            *ebpf.MapSpec `ebpf:"events"`
	FibGenMap         *ebpf.MapSpec `ebpf:"fib_gen_map"`
	FilterConfigs     *ebpf.MapSpec `ebpf:"filter_configs"`
	FilterCounters    *ebpf.MapSpec `ebpf:"filter_counters"`
	FilterRules       *ebpf.MapSpec `ebpf:"filter_rules"`
	FloodCounters     *ebpf.MapSpec `ebpf:"flood_counters"`
	FlowConfigMap     *ebpf.MapSpec `ebpf:"flow_config_map"`
	FlowTimeouts      *ebpf.MapSpec `ebpf:"flow_timeouts"`
	GlobalCounters    *ebpf.MapSpec `ebpf:"global_counters"`
	IfaceFilterMap    *ebpf.MapSpec `ebpf:"iface_filter_map"`
	IfaceZoneMap      *ebpf.MapSpec `ebpf:"iface_zone_map"`
	InterfaceCounters *ebpf.MapSpec `ebpf:"interface_counters"`
	IpSweepTrack      *ebpf.MapSpec `ebpf:"ip_sweep_track"`
	MirrorConfig      *ebpf.MapSpec `ebpf:"mirror_config"`
	MirrorCounter     *ebpf.MapSpec `ebpf:"mirror_counter"`
	Nat64Configs      *ebpf.MapSpec `ebpf:"nat64_configs"`
	Nat64Count        *ebpf.MapSpec `ebpf:"nat64_count"`
	Nat64PrefixMap    *ebpf.MapSpec `ebpf:"nat64_prefix_map"`
	Nat64State        *ebpf.MapSpec `ebpf:"nat64_state"`
	PktMetaScratch    *ebpf.MapSpec `ebpf:"pkt_meta_scratch"`
	PolicerConfigs    *ebpf.MapSpec `ebpf:"policer_configs"`
	PolicerStates     *ebpf.MapSpec `ebpf:"policer_states"`
	PolicyCounters    *ebpf.MapSpec `ebpf:"policy_counters"`
	PolicyRules       *ebpf.MapSpec `ebpf:"policy_rules"`
	PortScanTrack     *ebpf.MapSpec `ebpf:"port_scan_track"`
	RedirectCapable   *ebpf.MapSpec `ebpf:"redirect_capable"`
	ScreenConfigs     *ebpf.MapSpec `ebpf:"screen_configs"`
	SessionV4Scratch  *ebpf.MapSpec `ebpf:"session_v4_scratch"`
	SessionV6Scratch  *ebpf.MapSpec `ebpf:"session_v6_scratch"`
	Sessions          *ebpf.MapSpec `ebpf:"sessions"`
	SessionsV6        *ebpf.MapSpec `ebpf:"sessions_v6"`
	SnatRules         *ebpf.MapSpec `ebpf:"snat_rules"`
	SnatRulesV6       *ebpf.MapSpec `ebpf:"snat_rules_v6"`
	StaticNatV4       *ebpf.MapSpec `ebpf:"static_nat_v4"`
	StaticNatV6       *ebpf.MapSpec `ebpf:"static_nat_v6"`
	TcProgs           *ebpf.MapSpec `ebpf:"tc_progs"`
	TxPorts           *ebpf.MapSpec `ebpf:"tx_ports"`
	VlanIfaceMap      *ebpf.MapSpec `ebpf:"vlan_iface_map"`
	XdpProgs          *ebpf.MapSpec `ebpf:"xdp_progs"`
	ZoneConfigs       *ebpf.MapSpec `ebpf:"zone_configs"`
	ZoneCounters      *ebpf.MapSpec `ebpf:"zone_counters"`
	ZonePairPolicies  *ebpf.MapSpec `ebpf:"zone_pair_policies"`
}

// bpfrxXdpScreenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxXdpScreenVariableSpecs struct {
}

// bpfrxXdpScreenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxXdpScreenObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxXdpScreenObjects struct {
	bpfrxXdpScreenPrograms
	bpfrxXdpScreenMaps
	bpfrxXdpScreenVariables
}

func (o *bpfrxXdpScreenObjects) Close() error {
	return _BpfrxXdpScreenClose(
		&o.bpfrxXdpScreenPrograms,
		&o.bpfrxXdpScreenMaps,
	)
}

// bpfrxXdpScreenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxXdpScreenObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxXdpScreenMaps struct {
	AddressBookV4     *ebpf.Map `ebpf:"address_book_v4"`
	AddressBookV6     *ebpf.Map `ebpf:"address_book_v6"`
	AddressMembership *ebpf.Map `ebpf:"address_membership"`
	Applications      *ebpf.Map `ebpf:"applications"`
	CpuMap            *ebpf.Map `ebpf:"cpu_map"`
	CpumapAvailable   *ebpf.Map `ebpf:"cpumap_available"`
	DefaultPolicy     *ebpf.Map `ebpf:"default_policy"`
	DnatTable         *ebpf.Map `ebpf:"dnat_table"`
	DnatTableV6       *ebpf.Map `ebpf:"dnat_table_v6"`
	Events            *ebpf.Map `ebpf:"events"`
	FibGenMap         *ebpf.Map `ebpf:"fib_gen_map"`
	FilterConfigs     *ebpf.Map `ebpf:"filter_configs"`
	FilterCounters    *ebpf.Map `ebpf:"filter_counters"`
	FilterRules       *ebpf.Map `ebpf:"filter_rules"`
	FloodCounters     *ebpf.Map `ebpf:"flood_counters"`
	FlowConfigMap     *ebpf.Map `ebpf:"flow_config_map"`
	FlowTimeouts      *ebpf.Map `ebpf:"flow_timeouts"`
	GlobalCounters    *ebpf.Map `ebpf:"global_counters"`
	IfaceFilterMap    *ebpf.Map `ebpf:"iface_filter_map"`
	IfaceZoneMap      *ebpf.Map `ebpf:"iface_zone_map"`
	InterfaceCounters *ebpf.Map `ebpf:"interface_counters"`
	IpSweepTrack      *ebpf.Map `ebpf:"ip_sweep_track"`
	MirrorConfig      *ebpf.Map `ebpf:"mirror_config"`
	MirrorCounter     *ebpf.Map `ebpf:"mirror_counter"`
	Nat64Configs      *ebpf.Map `ebpf:"nat64_configs"`
	Nat64Count        *ebpf.Map `ebpf:"nat64_count"`
	Nat64PrefixMap    *ebpf.Map `ebpf:"nat64_prefix_map"`
	Nat64State        *ebpf.Map `ebpf:"nat64_state"`
	PktMetaScratch    *ebpf.Map `ebpf:"pkt_meta_scratch"`
	PolicerConfigs    *ebpf.Map `ebpf:"policer_configs"`
	PolicerStates     *ebpf.Map `ebpf:"policer_states"`
	PolicyCounters    *ebpf.Map `ebpf:"policy_counters"`
	PolicyRules       *ebpf.Map `ebpf:"policy_rules"`
	PortScanTrack     *ebpf.Map `ebpf:"port_scan_track"`
	RedirectCapable   *ebpf.Map `ebpf:"redirect_capable"`
	ScreenConfigs     *ebpf.Map `ebpf:"screen_configs"`
	SessionV4Scratch  *ebpf.Map `ebpf:"session_v4_scratch"`
	SessionV6Scratch  *ebpf.Map `ebpf:"session_v6_scratch"`
	Sessions          *ebpf.Map `ebpf:"sessions"`
	SessionsV6        *ebpf.Map `ebpf:"sessions_v6"`
	SnatRules         *ebpf.Map `ebpf:"snat_rules"`
	SnatRulesV6       *ebpf.Map `ebpf:"snat_rules_v6"`
	StaticNatV4       *ebpf.Map `ebpf:"static_nat_v4"`
	StaticNatV6       *ebpf.Map `ebpf:"static_nat_v6"`
	TcProgs           *ebpf.Map `ebpf:"tc_progs"`
	TxPorts           *ebpf.Map `ebpf:"tx_ports"`
	VlanIfaceMap      *ebpf.Map `ebpf:"vlan_iface_map"`
	XdpProgs          *ebpf.Map `ebpf:"xdp_progs"`
	ZoneConfigs       *ebpf.Map `ebpf:"zone_configs"`
	ZoneCounters      *ebpf.Map `ebpf:"zone_counters"`
	ZonePairPolicies  *ebpf.Map `ebpf:"zone_pair_policies"`
}

func (m *bpfrxXdpScreenMaps) Close() error {
	return _BpfrxXdpScreenClose(
		m.AddressBookV4,
		m.AddressBookV6,
		m.AddressMembership,
		m.Applications,
		m.CpuMap,
		m.CpumapAvailable,
		m.DefaultPolicy,
		m.DnatTable,
		m.DnatTableV6,
		m.Events,
		m.FibGenMap,
		m.FilterConfigs,
		m.FilterCounters,
		m.FilterRules,
		m.FloodCounters,
		m.FlowConfigMap,
		m.FlowTimeouts,
		m.GlobalCounters,
		m.IfaceFilterMap,
		m.IfaceZoneMap,
		m.InterfaceCounters,
		m.IpSweepTrack,
		m.MirrorConfig,
		m.MirrorCounter,
		m.Nat64Configs,
		m.Nat64Count,
		m.Nat64PrefixMap,
		m.Nat64State,
		m.PktMetaScratch,
		m.PolicerConfigs,
		m.PolicerStates,
		m.PolicyCounters,
		m.PolicyRules,
		m.PortScanTrack,
		m.RedirectCapable,
		m.ScreenConfigs,
		m.SessionV4Scratch,
		m.SessionV6Scratch,
		m.Sessions,
		m.SessionsV6,
		m.SnatRules,
		m.SnatRulesV6,
		m.StaticNatV4,
		m.StaticNatV6,
		m.TcProgs,
		m.TxPorts,
		m.VlanIfaceMap,
		m.XdpProgs,
		m.ZoneConfigs,
		m.ZoneCounters,
		m.ZonePairPolicies,
	)
}

// bpfrxXdpScreenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxXdpScreenObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxXdpScreenVariables struct {
}

// bpfrxXdpScreenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxXdpScreenObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxXdpScreenPrograms struct {
	XdpScreenProg *ebpf.Program `ebpf:"xdp_screen_prog"`
}

func (p *bpfrxXdpScreenPrograms) Close() error {
	return _BpfrxXdpScreenClose(
		p.XdpScreenProg,
	)
}

func _BpfrxXdpScreenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfrxxdpscreen_x86_bpfel.o
var _BpfrxXdpScreenBytes []byte
