// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfrxTcScreenEgressAddrMembershipKey struct {
	_         structs.HostLayout
	Ip        uint32
	AddressId uint32
}

type bpfrxTcScreenEgressAddrValue struct {
	_         structs.HostLayout
	AddressId uint32
}

type bpfrxTcScreenEgressAppKey struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      uint8
	DstPort  uint16
}

type bpfrxTcScreenEgressAppValue struct {
	_       structs.HostLayout
	AppId   uint32
	AlgType uint8
	Pad     [3]uint8
}

type bpfrxTcScreenEgressBpfDevmapVal struct {
	_       structs.HostLayout
	Ifindex uint32
	BpfProg struct {
		_  structs.HostLayout
		Fd int32
	}
}

type bpfrxTcScreenEgressCounterValue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type bpfrxTcScreenEgressDnatKey struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      [3]uint8
	DstIp    uint32
	DstPort  uint16
	Pad2     uint16
}

type bpfrxTcScreenEgressDnatKeyV6 struct {
	_        structs.HostLayout
	Protocol uint8
	Pad      [3]uint8
	DstIp    [16]uint8
	DstPort  uint16
	Pad2     uint16
}

type bpfrxTcScreenEgressDnatValue struct {
	_          structs.HostLayout
	NewDstIp   uint32
	NewDstPort uint16
	Flags      uint8
	Pad        uint8
}

type bpfrxTcScreenEgressDnatValueV6 struct {
	_          structs.HostLayout
	NewDstIp   [16]uint8
	NewDstPort uint16
	Flags      uint8
	Pad        uint8
}

type bpfrxTcScreenEgressFloodState struct {
	_           structs.HostLayout
	SynCount    uint64
	IcmpCount   uint64
	UdpCount    uint64
	WindowStart uint64
}

type bpfrxTcScreenEgressIfaceCounterValue struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
}

type bpfrxTcScreenEgressLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type bpfrxTcScreenEgressLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type bpfrxTcScreenEgressPktMeta struct {
	_     structs.HostLayout
	SrcIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	DstIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	SrcPort        uint16
	DstPort        uint16
	Protocol       uint8
	TcpFlags       uint8
	IpTtl          uint8
	AddrFamily     uint8
	IcmpId         uint16
	IcmpType       uint8
	IcmpCode       uint8
	TcpSeq         uint32
	TcpAckSeq      uint32
	L3Offset       uint16
	L4Offset       uint16
	PayloadOffset  uint16
	PktLen         uint16
	IngressZone    uint16
	EgressZone     uint16
	IngressIfindex uint32
	Direction      uint8
	IsFragment     uint8
	CtState        uint8
	CtDirection    uint8
	PolicyId       uint32
	NatSrcIp       struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	NatDstIp struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	NatSrcPort uint16
	NatDstPort uint16
	NatFlags   uint32
	FwdIfindex uint32
	FwdDmac    [6]uint8
	FwdSmac    [6]uint8
}

type bpfrxTcScreenEgressPolicyRule struct {
	_           structs.HostLayout
	RuleId      uint32
	PolicySetId uint32
	Sequence    uint16
	Action      uint8
	Log         uint8
	SrcAddrId   uint32
	DstAddrId   uint32
	DstPortLow  uint16
	DstPortHigh uint16
	Protocol    uint8
	Pad         [3]uint8
	AppId       uint32
	NatRuleId   uint32
	CounterId   uint32
}

type bpfrxTcScreenEgressPolicySet struct {
	_             structs.HostLayout
	PolicySetId   uint32
	NumRules      uint16
	DefaultAction uint16
}

type bpfrxTcScreenEgressScreenConfig struct {
	_               structs.HostLayout
	Flags           uint32
	SynFloodThresh  uint32
	IcmpFloodThresh uint32
	UdpFloodThresh  uint32
}

type bpfrxTcScreenEgressSessionKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfrxTcScreenEgressSessionKeyV6 struct {
	_        structs.HostLayout
	SrcIp    [16]uint8
	DstIp    [16]uint8
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type bpfrxTcScreenEgressSessionValue struct {
	_           structs.HostLayout
	State       uint8
	Flags       uint8
	TcpState    uint8
	IsReverse   uint8
	_           [4]byte
	Created     uint64
	LastSeen    uint64
	Timeout     uint32
	PolicyId    uint32
	IngressZone uint16
	EgressZone  uint16
	NatSrcIp    uint32
	NatDstIp    uint32
	NatSrcPort  uint16
	NatDstPort  uint16
	FwdPackets  uint64
	FwdBytes    uint64
	RevPackets  uint64
	RevBytes    uint64
	ReverseKey  bpfrxTcScreenEgressSessionKey
	AlgType     uint8
	LogFlags    uint8
	Pad         [2]uint8
	_           [4]byte
}

type bpfrxTcScreenEgressSessionValueV6 struct {
	_           structs.HostLayout
	State       uint8
	Flags       uint8
	TcpState    uint8
	IsReverse   uint8
	_           [4]byte
	Created     uint64
	LastSeen    uint64
	Timeout     uint32
	PolicyId    uint32
	IngressZone uint16
	EgressZone  uint16
	NatSrcIp    [16]uint8
	NatDstIp    [16]uint8
	NatSrcPort  uint16
	NatDstPort  uint16
	FwdPackets  uint64
	FwdBytes    uint64
	RevPackets  uint64
	RevBytes    uint64
	ReverseKey  bpfrxTcScreenEgressSessionKeyV6
	AlgType     uint8
	LogFlags    uint8
	Pad         [2]uint8
	_           [4]byte
}

type bpfrxTcScreenEgressSnatKey struct {
	_        structs.HostLayout
	FromZone uint16
	ToZone   uint16
	RuleIdx  uint16
	Pad      uint16
}

type bpfrxTcScreenEgressSnatValue struct {
	_         structs.HostLayout
	SnatIp    uint32
	SrcAddrId uint32
	DstAddrId uint32
	Mode      uint8
	Pad       [3]uint8
}

type bpfrxTcScreenEgressSnatValueV6 struct {
	_         structs.HostLayout
	SnatIp    [16]uint8
	SrcAddrId uint32
	DstAddrId uint32
	Mode      uint8
	Pad       [3]uint8
}

type bpfrxTcScreenEgressStaticNatKeyV4 struct {
	_         structs.HostLayout
	Ip        uint32
	Direction uint8
	Pad       [3]uint8
}

type bpfrxTcScreenEgressStaticNatKeyV6 struct {
	_         structs.HostLayout
	Ip        [16]uint8
	Direction uint8
	Pad       [3]uint8
}

type bpfrxTcScreenEgressStaticNatValueV6 struct {
	_  structs.HostLayout
	Ip [16]uint8
}

type bpfrxTcScreenEgressZoneConfig struct {
	_                structs.HostLayout
	ZoneId           uint16
	ScreenProfileId  uint16
	HostInboundFlags uint32
}

type bpfrxTcScreenEgressZonePairKey struct {
	_        structs.HostLayout
	FromZone uint16
	ToZone   uint16
}

// loadBpfrxTcScreenEgress returns the embedded CollectionSpec for bpfrxTcScreenEgress.
func loadBpfrxTcScreenEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfrxTcScreenEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfrxTcScreenEgress: %w", err)
	}

	return spec, err
}

// loadBpfrxTcScreenEgressObjects loads bpfrxTcScreenEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfrxTcScreenEgressObjects
//	*bpfrxTcScreenEgressPrograms
//	*bpfrxTcScreenEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfrxTcScreenEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfrxTcScreenEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfrxTcScreenEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxTcScreenEgressSpecs struct {
	bpfrxTcScreenEgressProgramSpecs
	bpfrxTcScreenEgressMapSpecs
	bpfrxTcScreenEgressVariableSpecs
}

// bpfrxTcScreenEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxTcScreenEgressProgramSpecs struct {
	TcScreenEgressProg *ebpf.ProgramSpec `ebpf:"tc_screen_egress_prog"`
}

// bpfrxTcScreenEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxTcScreenEgressMapSpecs struct {
	AddressBookV4     *ebpf.MapSpec `ebpf:"address_book_v4"`
	AddressBookV6     *ebpf.MapSpec `ebpf:"address_book_v6"`
	AddressMembership *ebpf.MapSpec `ebpf:"address_membership"`
	Applications      *ebpf.MapSpec `ebpf:"applications"`
	DefaultPolicy     *ebpf.MapSpec `ebpf:"default_policy"`
	DnatTable         *ebpf.MapSpec `ebpf:"dnat_table"`
	DnatTableV6       *ebpf.MapSpec `ebpf:"dnat_table_v6"`
	Events            *ebpf.MapSpec `ebpf:"events"`
	FloodCounters     *ebpf.MapSpec `ebpf:"flood_counters"`
	GlobalCounters    *ebpf.MapSpec `ebpf:"global_counters"`
	IfaceZoneMap      *ebpf.MapSpec `ebpf:"iface_zone_map"`
	InterfaceCounters *ebpf.MapSpec `ebpf:"interface_counters"`
	PktMetaScratch    *ebpf.MapSpec `ebpf:"pkt_meta_scratch"`
	PolicyCounters    *ebpf.MapSpec `ebpf:"policy_counters"`
	PolicyRules       *ebpf.MapSpec `ebpf:"policy_rules"`
	ScreenConfigs     *ebpf.MapSpec `ebpf:"screen_configs"`
	SessionV6Scratch  *ebpf.MapSpec `ebpf:"session_v6_scratch"`
	Sessions          *ebpf.MapSpec `ebpf:"sessions"`
	SessionsV6        *ebpf.MapSpec `ebpf:"sessions_v6"`
	SnatRules         *ebpf.MapSpec `ebpf:"snat_rules"`
	SnatRulesV6       *ebpf.MapSpec `ebpf:"snat_rules_v6"`
	StaticNatV4       *ebpf.MapSpec `ebpf:"static_nat_v4"`
	StaticNatV6       *ebpf.MapSpec `ebpf:"static_nat_v6"`
	TcProgs           *ebpf.MapSpec `ebpf:"tc_progs"`
	TxPorts           *ebpf.MapSpec `ebpf:"tx_ports"`
	XdpProgs          *ebpf.MapSpec `ebpf:"xdp_progs"`
	ZoneConfigs       *ebpf.MapSpec `ebpf:"zone_configs"`
	ZoneCounters      *ebpf.MapSpec `ebpf:"zone_counters"`
	ZonePairPolicies  *ebpf.MapSpec `ebpf:"zone_pair_policies"`
}

// bpfrxTcScreenEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfrxTcScreenEgressVariableSpecs struct {
}

// bpfrxTcScreenEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxTcScreenEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxTcScreenEgressObjects struct {
	bpfrxTcScreenEgressPrograms
	bpfrxTcScreenEgressMaps
	bpfrxTcScreenEgressVariables
}

func (o *bpfrxTcScreenEgressObjects) Close() error {
	return _BpfrxTcScreenEgressClose(
		&o.bpfrxTcScreenEgressPrograms,
		&o.bpfrxTcScreenEgressMaps,
	)
}

// bpfrxTcScreenEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxTcScreenEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxTcScreenEgressMaps struct {
	AddressBookV4     *ebpf.Map `ebpf:"address_book_v4"`
	AddressBookV6     *ebpf.Map `ebpf:"address_book_v6"`
	AddressMembership *ebpf.Map `ebpf:"address_membership"`
	Applications      *ebpf.Map `ebpf:"applications"`
	DefaultPolicy     *ebpf.Map `ebpf:"default_policy"`
	DnatTable         *ebpf.Map `ebpf:"dnat_table"`
	DnatTableV6       *ebpf.Map `ebpf:"dnat_table_v6"`
	Events            *ebpf.Map `ebpf:"events"`
	FloodCounters     *ebpf.Map `ebpf:"flood_counters"`
	GlobalCounters    *ebpf.Map `ebpf:"global_counters"`
	IfaceZoneMap      *ebpf.Map `ebpf:"iface_zone_map"`
	InterfaceCounters *ebpf.Map `ebpf:"interface_counters"`
	PktMetaScratch    *ebpf.Map `ebpf:"pkt_meta_scratch"`
	PolicyCounters    *ebpf.Map `ebpf:"policy_counters"`
	PolicyRules       *ebpf.Map `ebpf:"policy_rules"`
	ScreenConfigs     *ebpf.Map `ebpf:"screen_configs"`
	SessionV6Scratch  *ebpf.Map `ebpf:"session_v6_scratch"`
	Sessions          *ebpf.Map `ebpf:"sessions"`
	SessionsV6        *ebpf.Map `ebpf:"sessions_v6"`
	SnatRules         *ebpf.Map `ebpf:"snat_rules"`
	SnatRulesV6       *ebpf.Map `ebpf:"snat_rules_v6"`
	StaticNatV4       *ebpf.Map `ebpf:"static_nat_v4"`
	StaticNatV6       *ebpf.Map `ebpf:"static_nat_v6"`
	TcProgs           *ebpf.Map `ebpf:"tc_progs"`
	TxPorts           *ebpf.Map `ebpf:"tx_ports"`
	XdpProgs          *ebpf.Map `ebpf:"xdp_progs"`
	ZoneConfigs       *ebpf.Map `ebpf:"zone_configs"`
	ZoneCounters      *ebpf.Map `ebpf:"zone_counters"`
	ZonePairPolicies  *ebpf.Map `ebpf:"zone_pair_policies"`
}

func (m *bpfrxTcScreenEgressMaps) Close() error {
	return _BpfrxTcScreenEgressClose(
		m.AddressBookV4,
		m.AddressBookV6,
		m.AddressMembership,
		m.Applications,
		m.DefaultPolicy,
		m.DnatTable,
		m.DnatTableV6,
		m.Events,
		m.FloodCounters,
		m.GlobalCounters,
		m.IfaceZoneMap,
		m.InterfaceCounters,
		m.PktMetaScratch,
		m.PolicyCounters,
		m.PolicyRules,
		m.ScreenConfigs,
		m.SessionV6Scratch,
		m.Sessions,
		m.SessionsV6,
		m.SnatRules,
		m.SnatRulesV6,
		m.StaticNatV4,
		m.StaticNatV6,
		m.TcProgs,
		m.TxPorts,
		m.XdpProgs,
		m.ZoneConfigs,
		m.ZoneCounters,
		m.ZonePairPolicies,
	)
}

// bpfrxTcScreenEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxTcScreenEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxTcScreenEgressVariables struct {
}

// bpfrxTcScreenEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfrxTcScreenEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfrxTcScreenEgressPrograms struct {
	TcScreenEgressProg *ebpf.Program `ebpf:"tc_screen_egress_prog"`
}

func (p *bpfrxTcScreenEgressPrograms) Close() error {
	return _BpfrxTcScreenEgressClose(
		p.TcScreenEgressProg,
	)
}

func _BpfrxTcScreenEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfrxtcscreenegress_x86_bpfel.o
var _BpfrxTcScreenEgressBytes []byte
