package dataplane

// #4977: source→object freshness gate for the git-tracked
// userspace_xdp_bpfel.o embedded by userspace_xdp_rust.go.
//
// `make build` is a plain `go build` and by design never runs `make
// generate`; `make test` never rebuilds the shim. So a logic-only edit
// to userspace-xdp/** source (a packet-steering or security fix) that
// is NOT followed by `make generate` + committing the regenerated .o
// would ship the STALE embedded object while source review and `make
// test` stay green. The existing canaries only bind program/map
// allowlists, max_entries sizing (validateUserspaceShimSpec), and a
// `go generate -n` dry-run — none proves the tracked object corresponds
// to CURRENT source.
//
// This manifest records a deterministic SHA-256 of every
// freshness-relevant shim build input AND of the tracked object itself.
// TestUserspaceXDPShimObjectMatchesSourceManifest recomputes both from
// the working tree and fails when they drift, telling the operator to
// run `make generate`. The manifest is regenerated ONLY by
// build-userspace-xdp.sh (via cmd/shim-manifest), immediately after the
// verifier-gated install of the object, so it stays in lockstep with
// the object it describes — the manifest can never record a source hash
// newer than the object that source produced.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/psaab/xpf/pkg/fsatomic"
)

const (
	// UserspaceXDPManifestRelPath is the repo-relative path to the
	// committed freshness manifest.
	UserspaceXDPManifestRelPath = "pkg/dataplane/userspace_xdp_manifest.json"

	// userspaceXDPObjectRelPath is the tracked shim object embedded by
	// userspace_xdp_rust.go (`//go:embed userspace_xdp_bpfel.o`).
	userspaceXDPObjectRelPath = "pkg/dataplane/userspace_xdp_bpfel.o"

	// userspaceXDPSourceDir holds the Rust sources compiled into the
	// shim. Every *.rs beneath it (recursively) is a freshness input, so
	// adding a new module file is caught by the manifest gate. Scoped to
	// src/ only so cargo's target/ build artifacts are never walked.
	userspaceXDPSourceDir = "userspace-xdp/src"

	userspaceXDPManifestComment = "GENERATED by `make generate` " +
		"(pkg/dataplane/build-userspace-xdp.sh via cmd/shim-manifest) — DO NOT EDIT BY HAND. " +
		"A TestUserspaceXDPShimObjectMatchesSourceManifest mismatch means " +
		"pkg/dataplane/userspace_xdp_bpfel.o is stale versus userspace-xdp/** source; " +
		"run `make generate`. See pkg/dataplane/README.md (#4977)."
)

// userspaceXDPFixedFreshnessInputs are the non-.rs build inputs that
// determine the shim object's bytes: the Cargo manifest + locked
// dependency graph, the pinned Rust toolchain, BOTH the crate-local and
// the repo-root cargo config (cargo loads ancestor configs too, so a
// root-level BPF-target rustflags edit could change the .o — currently
// inert x86_64, hashed for completeness), the build recipe itself
// (build-userspace-xdp.sh embeds the bpf-linker version pin and threads
// MAX_INTERFACES), and bpf/headers/xpf_common.h (whose MAX_INTERFACES
// #define is awk-extracted by the recipe and sizes the shim's binding
// array + maps). Paths are repo-relative POSIX.
//
// xpf_common.h is hashed directly here so the freshness gate is
// self-sufficient: the header->Go max_entries parity canary
// (TestMaxInterfacesMatchesCHeader) t.Skips when the header is absent, so
// leaning on it alone left a fail-open hole. Whole-file hashing trades a
// little churn on unrelated header edits for a fail-closed gate.
//
// Deliberately EXCLUDED: userspace-xdp/.gitignore (not a build input) and
// cargo's target/ tree (build artifacts, untracked).
var userspaceXDPFixedFreshnessInputs = []string{
	".cargo/config.toml",
	"bpf/headers/xpf_common.h",
	"pkg/dataplane/build-userspace-xdp.sh",
	"userspace-xdp/.cargo/config.toml",
	"userspace-xdp/Cargo.lock",
	"userspace-xdp/Cargo.toml",
	"userspace-xdp/rust-toolchain.toml",
}

type shimManifestEntry struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

type shimFreshnessManifest struct {
	Comment string            `json:"_comment"`
	Object  shimManifestEntry `json:"object"`
	// ShimFacts are the object's SELF-REPORTED compile-time values
	// (#4555), read back out of the object via ReadShimFactsFromObject
	// rather than modelled from the shim's source. Recording them here
	// makes them travel with the artifact: a consumer of a prebuilt
	// object (the Debian packaging path never compiles the shim crate)
	// checks the same numbers the generator measured.
	ShimFacts *ShimFacts          `json:"shim_facts"`
	Inputs    []shimManifestEntry `json:"inputs"`
}

// userspaceXDPFreshnessInputPaths returns the sorted, repo-relative set
// of freshness-relevant shim build inputs: the fixed set above plus
// every *.rs under userspace-xdp/src. It errors if any fixed input is
// missing so an input can never be silently dropped from the manifest.
func userspaceXDPFreshnessInputPaths(repoRoot string) ([]string, error) {
	paths := make([]string, 0, len(userspaceXDPFixedFreshnessInputs)+4)
	for _, rel := range userspaceXDPFixedFreshnessInputs {
		abs := filepath.Join(repoRoot, filepath.FromSlash(rel))
		if _, err := os.Stat(abs); err != nil {
			return nil, fmt.Errorf("freshness input %q: %w", rel, err)
		}
		paths = append(paths, rel)
	}

	srcRoot := filepath.Join(repoRoot, filepath.FromSlash(userspaceXDPSourceDir))
	walkErr := filepath.WalkDir(srcRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".rs") {
			return nil
		}
		rel, err := filepath.Rel(repoRoot, p)
		if err != nil {
			return err
		}
		paths = append(paths, filepath.ToSlash(rel))
		return nil
	})
	if walkErr != nil {
		return nil, fmt.Errorf("walk %s: %w", userspaceXDPSourceDir, walkErr)
	}

	sort.Strings(paths)
	return paths, nil
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// ComputeUserspaceXDPManifest builds the freshness manifest from the
// working tree rooted at repoRoot (repo-relative paths).
func ComputeUserspaceXDPManifest(repoRoot string) (*shimFreshnessManifest, error) {
	objAbs := filepath.Join(repoRoot, filepath.FromSlash(userspaceXDPObjectRelPath))
	objHash, err := sha256File(objAbs)
	if err != nil {
		return nil, fmt.Errorf("hash shim object %q: %w", userspaceXDPObjectRelPath, err)
	}

	inputs, err := userspaceXDPFreshnessInputPaths(repoRoot)
	if err != nil {
		return nil, err
	}
	entries := make([]shimManifestEntry, 0, len(inputs))
	for _, rel := range inputs {
		h, err := sha256File(filepath.Join(repoRoot, filepath.FromSlash(rel)))
		if err != nil {
			return nil, fmt.Errorf("hash input %q: %w", rel, err)
		}
		entries = append(entries, shimManifestEntry{Path: rel, SHA256: h})
	}

	facts, err := ReadShimFactsFromObject(objAbs)
	if err != nil {
		return nil, fmt.Errorf("read emitted shim facts (#4555): %w", err)
	}

	return &shimFreshnessManifest{
		Comment:   userspaceXDPManifestComment,
		Object:    shimManifestEntry{Path: userspaceXDPObjectRelPath, SHA256: objHash},
		ShimFacts: facts,
		Inputs:    entries,
	}, nil
}

// MarshalUserspaceXDPManifest renders the manifest deterministically as
// indented JSON with a trailing newline. Struct field order (Comment,
// Object, Inputs) and the sorted Inputs slice make the output stable, so
// a regenerated manifest yields a clean git diff when nothing changed.
func MarshalUserspaceXDPManifest(m *shimFreshnessManifest) ([]byte, error) {
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func parseUserspaceXDPManifest(b []byte) (*shimFreshnessManifest, error) {
	var m shimFreshnessManifest
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

// WriteUserspaceXDPManifest recomputes and writes the manifest to
// repoRoot/UserspaceXDPManifestRelPath. It is invoked by
// build-userspace-xdp.sh (through cmd/shim-manifest) right after the
// verifier-gated install of the shim object.
func WriteUserspaceXDPManifest(repoRoot string) error {
	m, err := ComputeUserspaceXDPManifest(repoRoot)
	if err != nil {
		return err
	}
	b, err := MarshalUserspaceXDPManifest(m)
	if err != nil {
		return err
	}
	out := filepath.Join(repoRoot, filepath.FromSlash(UserspaceXDPManifestRelPath))
	// Atomic write (pkg/fsatomic) rather than os.WriteFile: the project's
	// TestNoDirectOsWriteFile canary forbids raw os.WriteFile in pkg/, and a
	// torn manifest (partial write on a crash mid-generate) would fail the
	// freshness test with a corrupt-file error rather than a clean stale
	// signal. temp-then-rename keeps the committed manifest always intact.
	return fsatomic.WriteFileAtomic(out, b, 0o644)
}
