// Package system holds pure, testable renderers for system-level
// configuration artifacts the daemon writes (DNS resolver config, etc.).
//
// The renderers here take plain value inputs and return strings with no
// filesystem or systemctl side effects, so they can be unit tested
// directly and reused by sibling packages without importing daemon
// internals. The daemon's apply/executor wrappers (e.g.
// daemon_system.go applySystemDNS) call these and handle the write,
// idempotence comparison, and service restart.
package system

import (
	"fmt"
	"strings"
)

// ResolvedDropinInput is the subset of system configuration that drives
// the systemd-resolved drop-in render. It is a plain value type so
// RenderResolvedDropin stays a pure function with no daemon/config
// package dependency.
type ResolvedDropinInput struct {
	// NameServers are the DNS server addresses (system name-server).
	NameServers []string
	// DomainName is the primary/search domain (system domain-name).
	DomainName string
	// DomainSearch is the additional search-domain list
	// (system domain-search).
	DomainSearch []string
}

// Empty reports whether there is no DNS configuration to render. The
// caller uses this to decide between writing and removing the drop-in.
// It is exactly the negation of "any DNS field set".
func (in ResolvedDropinInput) Empty() bool {
	return len(in.NameServers) == 0 && in.DomainName == "" && len(in.DomainSearch) == 0
}

// RenderResolvedDropin returns the full text of the
// /etc/systemd/resolved.conf.d/xpf.conf drop-in for the given input, or
// "" when in.Empty().
//
// It combines domain-name and domain-search into a single Domains=
// list (domain-name first, then the search domains in config order,
// with any search entry equal to a non-empty domain-name dropped as a
// redundant duplicate). systemd-resolved's Domains= directive accepts a
// space-separated list of search domains processed in order, so both
// the primary domain and the explicit search domains must appear on the
// one line. The previous else-if form silently dropped the search list
// whenever domain-name was also set (#1713).
func RenderResolvedDropin(in ResolvedDropinInput) string {
	if in.Empty() {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by xpfd — do not edit\n[Resolve]\n")
	if len(in.NameServers) > 0 {
		fmt.Fprintf(&b, "DNS=%s\n", strings.Join(in.NameServers, " "))
	}
	if domains := combinedDomains(in.DomainName, in.DomainSearch); len(domains) > 0 {
		fmt.Fprintf(&b, "Domains=%s\n", strings.Join(domains, " "))
	}
	return b.String()
}

// combinedDomains builds the ordered Domains= list: domain-name first
// (when set), then each search domain in order. A search entry is
// skipped only when domain-name is non-empty and string-equals it, so
// the redundant second occurrence of the primary domain is removed
// without reordering any distinct suffix and without dropping an
// empty-string element when domain-name is unset.
func combinedDomains(domainName string, search []string) []string {
	out := make([]string, 0, 1+len(search))
	if domainName != "" {
		out = append(out, domainName)
	}
	for _, d := range search {
		if domainName != "" && d == domainName {
			continue
		}
		out = append(out, d)
	}
	return out
}

// resolvConfHeader marks the file as xpf-managed. The reconciler
// compares the full rendered text byte-for-byte for idempotence, so the
// header must stay stable.
const resolvConfHeader = "# Generated by xpfd — do not edit\n"

// RenderResolvConf returns the full text of a plain /etc/resolv.conf
// (resolv.conf(5) format) that xpf owns directly, with no dependency on
// systemd-resolved. This is the #1715 ownership model: xpf manages
// /etc/resolv.conf as a managed plain file rather than delegating to a
// resolved drop-in (RenderResolvedDropin, above).
//
// Output:
//   - one `nameserver <addr>` line per server, in the order given;
//   - a single `search <d1> <d2> ...` line built from domain-name first
//     (when set) then the search domains in config order, with a search
//     entry equal to a non-empty domain-name dropped as a redundant
//     duplicate (mirrors combinedDomains so the two renderers agree on
//     domain handling).
//
// resolv.conf(5) supports `domain` (single) and `search` (list) and
// treats `domain` as equivalent to a one-element `search`; the last of
// the two in the file wins. We always emit `search` so the combined
// domain-name + domain-search list survives — emitting a separate
// `domain` line would be overridden by `search` (and vice versa).
//
// When there is no DNS configuration at all the result is a header-only
// comment file. That is intentional: the reconciler writes this to
// replace a dangling/stub symlink at boot or to clear DNS when the last
// name-server / lease goes away, leaving a valid (empty) resolver file
// rather than a dangling symlink.
func RenderResolvConf(in ResolvedDropinInput) string {
	var b strings.Builder
	b.WriteString(resolvConfHeader)
	for _, ns := range in.NameServers {
		fmt.Fprintf(&b, "nameserver %s\n", ns)
	}
	if domains := combinedDomains(in.DomainName, in.DomainSearch); len(domains) > 0 {
		fmt.Fprintf(&b, "search %s\n", strings.Join(domains, " "))
	}
	return b.String()
}
