package system

import "testing"

const dropinHeader = "# Generated by xpfd — do not edit\n[Resolve]\n"

func TestRenderResolvedDropin(t *testing.T) {
	tests := []struct {
		name string
		in   ResolvedDropinInput
		want string
	}{
		{
			name: "empty renders nothing",
			in:   ResolvedDropinInput{},
			want: "",
		},
		{
			name: "nameservers only",
			in:   ResolvedDropinInput{NameServers: []string{"1.1.1.1", "8.8.8.8"}},
			want: dropinHeader + "DNS=1.1.1.1 8.8.8.8\n",
		},
		{
			name: "domain-name only renders bare search domain",
			in:   ResolvedDropinInput{DomainName: "example.com"},
			want: dropinHeader + "Domains=example.com\n",
		},
		{
			name: "domain-search only",
			in:   ResolvedDropinInput{DomainSearch: []string{"corp.example.com", "lab.example.com"}},
			want: dropinHeader + "Domains=corp.example.com lab.example.com\n",
		},
		{
			name: "DNS plus domain-name keeps DNS before Domains",
			in: ResolvedDropinInput{
				NameServers: []string{"1.1.1.1"},
				DomainName:  "example.com",
			},
			want: dropinHeader + "DNS=1.1.1.1\n" + "Domains=example.com\n",
		},
		{
			name: "DNS plus domain-search keeps DNS before Domains",
			in: ResolvedDropinInput{
				NameServers:  []string{"1.1.1.1"},
				DomainSearch: []string{"corp.example.com"},
			},
			want: dropinHeader + "DNS=1.1.1.1\n" + "Domains=corp.example.com\n",
		},
		{
			// The #1713 regression case: both domain-name and
			// domain-search set must combine into one Domains= line
			// (domain-name first) rather than dropping the search list.
			name: "combined domain-name and domain-search (the #1713 case)",
			in: ResolvedDropinInput{
				NameServers:  []string{"1.1.1.1", "8.8.8.8"},
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "lab.example.com"},
			},
			want: dropinHeader +
				"DNS=1.1.1.1 8.8.8.8\n" +
				"Domains=example.com corp.example.com lab.example.com\n",
		},
		{
			// De-dup: a search entry equal to the (non-empty)
			// domain-name is dropped so the primary domain is not
			// repeated; distinct suffixes keep their order.
			name: "domain-name duplicated in search is de-duplicated",
			in: ResolvedDropinInput{
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "example.com", "lab.example.com"},
			},
			want: dropinHeader + "Domains=example.com corp.example.com lab.example.com\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := RenderResolvedDropin(tt.in)
			if got != tt.want {
				t.Errorf("RenderResolvedDropin(%+v)\n got: %q\nwant: %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestResolvedDropinInputEmpty(t *testing.T) {
	tests := []struct {
		name string
		in   ResolvedDropinInput
		want bool
	}{
		{"all unset", ResolvedDropinInput{}, true},
		{"nameservers set", ResolvedDropinInput{NameServers: []string{"1.1.1.1"}}, false},
		{"domain-name set", ResolvedDropinInput{DomainName: "example.com"}, false},
		{"domain-search set", ResolvedDropinInput{DomainSearch: []string{"corp.example.com"}}, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.in.Empty(); got != tt.want {
				t.Errorf("Empty(%+v) = %v, want %v", tt.in, got, tt.want)
			}
		})
	}
}
