package system

import "testing"

const dropinHeader = "# Generated by xpfd — do not edit\n[Resolve]\n"

func TestRenderResolvedDropin(t *testing.T) {
	tests := []struct {
		name string
		in   ResolvedDropinInput
		want string
	}{
		{
			name: "empty renders nothing",
			in:   ResolvedDropinInput{},
			want: "",
		},
		{
			name: "nameservers only",
			in:   ResolvedDropinInput{NameServers: []string{"1.1.1.1", "8.8.8.8"}},
			want: dropinHeader + "DNS=1.1.1.1 8.8.8.8\n",
		},
		{
			name: "domain-name only renders bare search domain",
			in:   ResolvedDropinInput{DomainName: "example.com"},
			want: dropinHeader + "Domains=example.com\n",
		},
		{
			name: "domain-search only",
			in:   ResolvedDropinInput{DomainSearch: []string{"corp.example.com", "lab.example.com"}},
			want: dropinHeader + "Domains=corp.example.com lab.example.com\n",
		},
		{
			name: "DNS plus domain-name keeps DNS before Domains",
			in: ResolvedDropinInput{
				NameServers: []string{"1.1.1.1"},
				DomainName:  "example.com",
			},
			want: dropinHeader + "DNS=1.1.1.1\n" + "Domains=example.com\n",
		},
		{
			name: "DNS plus domain-search keeps DNS before Domains",
			in: ResolvedDropinInput{
				NameServers:  []string{"1.1.1.1"},
				DomainSearch: []string{"corp.example.com"},
			},
			want: dropinHeader + "DNS=1.1.1.1\n" + "Domains=corp.example.com\n",
		},
		{
			// The #1713 regression case: both domain-name and
			// domain-search set must combine into one Domains= line
			// (domain-name first) rather than dropping the search list.
			name: "combined domain-name and domain-search (the #1713 case)",
			in: ResolvedDropinInput{
				NameServers:  []string{"1.1.1.1", "8.8.8.8"},
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "lab.example.com"},
			},
			want: dropinHeader +
				"DNS=1.1.1.1 8.8.8.8\n" +
				"Domains=example.com corp.example.com lab.example.com\n",
		},
		{
			// Compatibility invariant: with no domain-name, the
			// de-dup guard must NOT drop an empty-string search
			// element, so the render matches the old
			// strings.Join(search, " ") byte-for-byte. (Parser-
			// unreachable today, but the guard keeps the renderer
			// total and pins the divergence-free behavior.)
			name: "empty-string search element is preserved when domain-name unset",
			in:   ResolvedDropinInput{DomainSearch: []string{""}},
			want: dropinHeader + "Domains=\n",
		},
		{
			// De-dup: a search entry equal to the (non-empty)
			// domain-name is dropped so the primary domain is not
			// repeated; distinct suffixes keep their order.
			name: "domain-name duplicated in search is de-duplicated",
			in: ResolvedDropinInput{
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "example.com", "lab.example.com"},
			},
			want: dropinHeader + "Domains=example.com corp.example.com lab.example.com\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := RenderResolvedDropin(tt.in)
			if got != tt.want {
				t.Errorf("RenderResolvedDropin(%+v)\n got: %q\nwant: %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestRenderResolvConf(t *testing.T) {
	const hdr = "# Generated by xpfd — do not edit\n"
	tests := []struct {
		name string
		in   ResolvedDropinInput
		want string
	}{
		{
			name: "empty renders header-only comment file",
			in:   ResolvedDropinInput{},
			want: hdr,
		},
		{
			name: "nameservers only, one line each, order preserved",
			in:   ResolvedDropinInput{NameServers: []string{"1.1.1.1", "8.8.8.8"}},
			want: hdr + "nameserver 1.1.1.1\nnameserver 8.8.8.8\n",
		},
		{
			name: "domain-name only renders search line",
			in:   ResolvedDropinInput{DomainName: "example.com"},
			want: hdr + "search example.com\n",
		},
		{
			name: "domain-search only renders search list",
			in:   ResolvedDropinInput{DomainSearch: []string{"corp.example.com", "lab.example.com"}},
			want: hdr + "search corp.example.com lab.example.com\n",
		},
		{
			name: "nameservers then search, combined domain-name + domain-search",
			in: ResolvedDropinInput{
				NameServers:  []string{"1.1.1.1", "8.8.8.8"},
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "lab.example.com"},
			},
			want: hdr +
				"nameserver 1.1.1.1\nnameserver 8.8.8.8\n" +
				"search example.com corp.example.com lab.example.com\n",
		},
		{
			name: "domain-name duplicated in search is de-duplicated",
			in: ResolvedDropinInput{
				DomainName:   "example.com",
				DomainSearch: []string{"corp.example.com", "example.com", "lab.example.com"},
			},
			want: hdr + "search example.com corp.example.com lab.example.com\n",
		},
		{
			name: "nameservers without any domain renders no search line",
			in:   ResolvedDropinInput{NameServers: []string{"9.9.9.9"}},
			want: hdr + "nameserver 9.9.9.9\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := RenderResolvConf(tt.in)
			if got != tt.want {
				t.Errorf("RenderResolvConf(%+v)\n got: %q\nwant: %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestResolvedDropinInputEmpty(t *testing.T) {
	tests := []struct {
		name string
		in   ResolvedDropinInput
		want bool
	}{
		{"all unset", ResolvedDropinInput{}, true},
		{"nameservers set", ResolvedDropinInput{NameServers: []string{"1.1.1.1"}}, false},
		{"domain-name set", ResolvedDropinInput{DomainName: "example.com"}, false},
		{"domain-search set", ResolvedDropinInput{DomainSearch: []string{"corp.example.com"}}, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.in.Empty(); got != tt.want {
				t.Errorf("Empty(%+v) = %v, want %v", tt.in, got, tt.want)
			}
		})
	}
}
