#!/usr/bin/env bash
# Periodic heatmap refresh job (#7253).
#
# Regenerates docs/refactoring-audit-current.txt from the committed
# generator and COMMITS the result, so global freshness converges without
# a human being interrupted for it.
#
# This is the demoted half of the old TestHeatmapNotStale. That test
# fused a modularity signal ("a file is growing past the point where it
# should be split") with a freshness signal ("the committed global
# snapshot disagrees with the tree") and made both fatal. The freshness
# half could not stay true: the artifact is a snapshot of a repo-GLOBAL
# property, so on a board landing several PRs an hour a PR that
# regenerates it correctly at its own base still lands stale because a
# sibling grew a different file in between. #7235, #7252 and #7254 all
# regenerated it inside one hour, and #7252 was ALREADY STALE when it
# merged. The modularity half now lives in pkg/refactoraudit's
# touched-file gate (scripts/refactoring-audit-touched.sh), which is
# derived from the PR's own diff and cannot go stale. What is left here
# is bookkeeping, and bookkeeping belongs to a job.
#
# Direct-push posture: --push is the docs-only maintenance carve-out from
# docs/engineering-style.md first principle #6 (the same one /sync-history
# uses). It is OFF by default; the script commits locally and prints what
# it did. A timer wires it as:
#
#   git -C <repo> fetch origin master && git -C <repo> checkout master &&
#   git -C <repo> merge --ff-only origin/master &&
#   bash scripts/refactoring-audit-refresh.sh --push
#
# Usage:
#   refactoring-audit-refresh.sh            regenerate + commit if stale
#   refactoring-audit-refresh.sh --check    report only; exit 1 if stale
#   refactoring-audit-refresh.sh --push     also push the refresh commit
set -euo pipefail

prog="$(basename "$0")"
check_only=no
push=no
for arg in "$@"; do
    case "$arg" in
        --check) check_only=yes ;;
        --push)  push=yes ;;
        -h|--help)
            echo "usage: $prog [--check] [--push]" >&2
            exit 0
            ;;
        *)
            echo "$prog: unknown argument '$arg'" >&2
            echo "usage: $prog [--check] [--push]" >&2
            exit 2
            ;;
    esac
done

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

artifact="docs/refactoring-audit-current.txt"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

bash scripts/refactoring-audit.sh > "$tmp"

# Fail closed on a broken generator: an empty regeneration would
# otherwise be committed as "every file left the audit".
if [ ! -s "$tmp" ]; then
    echo "$prog: scripts/refactoring-audit.sh produced no rows; refusing to commit an empty heatmap" >&2
    exit 1
fi

if [ -f "$artifact" ] && cmp -s "$tmp" "$artifact"; then
    echo "$prog: $artifact is up to date"
    exit 0
fi

echo "$prog: $artifact is stale:"
diff -u "$artifact" "$tmp" || true

if [ "$check_only" = yes ]; then
    echo "$prog: --check, not committing"
    exit 1
fi

mkdir -p "$(dirname "$artifact")"
cp "$tmp" "$artifact"

# Commit ONLY the artifact path. A pathspec commit takes the working-tree
# content of that path and leaves everything else — including a dirty
# index — alone, so the job cannot sweep an unrelated edit into its own
# commit.
head_sha="$(git rev-parse --short HEAD)"
git add -- "$artifact"
git commit -q -m "docs: refresh the refactoring audit heatmap

Regenerated by scripts/${prog} at ${head_sha} with the committed
generator (scripts/refactoring-audit.sh). The heatmap is a snapshot of a
repo-global property, so it goes stale whenever any audited file crosses
1500 or 2000 LOC; converging it is this job's work rather than a PR
author's (#7253)." -- "$artifact"
echo "$prog: committed $(git rev-parse --short HEAD)"

if [ "$push" = yes ]; then
    git push
    echo "$prog: pushed"
fi
