/*
 * Test xsk_socket__create_shared specifically.
 * The previous test used xsk_socket__create (non-shared) which worked (rx=3).
 * This test uses create_shared to determine if the shared path has a bug.
 *
 * Build (embeds the XDP object; run via the Makefile which generates
 * xdp_pass_redirect_obj.h from the tracked xdp_pass_redirect.o):
 *   make libbpf-xsk-shared-test
 *
 * Usage:
 *   ./libbpf-xsk-shared-test <owner-iface> <owner-queue> [copy|zerocopy]
 *   ./libbpf-xsk-shared-test <owner-iface> <owner-queue> \
 *       <secondary-iface> <secondary-queue> [copy|zerocopy]
 *
 * Must run as root. The XDP object is compiled in and loaded from memory
 * (bpf_object__open_mem, #4906 HC-025), attached with UPDATE_IF_NOEXIST and
 * detached only if still ours (#4906 HC-101). When a secondary socket is
 * configured the test actually drives it (fill + poll + recycle) and folds its
 * receive count into PASS/FAIL (#4906 HC-095).
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <poll.h>
#include <time.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <net/if.h>
#include <linux/if_link.h>
#include <linux/if_xdp.h>
#include <linux/bpf.h>
#include <bpf/bpf.h>
#include <bpf/libbpf.h>
#include <xdp/xsk.h>

/* Embedded xdp_pass_redirect.o (generated by the Makefile via `xxd -i`). */
#include "xdp_pass_redirect_obj.h"

#define FRAME_SIZE  4096
#define NUM_FRAMES  4096
#define BATCH_SIZE  64

static int xsk_reports_zerocopy(int fd)
{
    struct xdp_options opts;
    socklen_t optlen = sizeof(opts);
    memset(&opts, 0, sizeof(opts));
    if (getsockopt(fd, SOL_XDP, XDP_OPTIONS, &opts, &optlen) != 0)
        return -1;
    return (opts.flags & XDP_OPTIONS_ZEROCOPY) != 0;
}

static int load_xdp(int ifindex, int *map_fd_out)
{
    /* #4906 HC-025: load from the compiled-in object bytes, not a predictable
     * /tmp path (no symlink/TOCTOU, no chance of loading a substituted object
     * as root). */
    struct bpf_object *obj =
        bpf_object__open_mem(xdp_pass_redirect_o, xdp_pass_redirect_o_len, NULL);
    if (!obj) { fprintf(stderr, "open_mem failed\n"); return -1; }
    if (bpf_object__load(obj)) { fprintf(stderr, "load failed\n"); return -1; }
    struct bpf_program *prog = bpf_object__find_program_by_name(obj, "xdp_redirect_xsk");
    if (!prog) { fprintf(stderr, "prog not found\n"); return -1; }
    struct bpf_map *map = bpf_object__find_map_by_name(obj, "xsk_map");
    if (!map) { fprintf(stderr, "map not found\n"); return -1; }
    *map_fd_out = bpf_map__fd(map);
    int prog_fd = bpf_program__fd(prog);
    /* #4906 HC-101: never replace an XDP program already on the interface. */
    int err = bpf_xdp_attach(ifindex, prog_fd, XDP_FLAGS_UPDATE_IF_NOEXIST, NULL);
    if (err) {
        if (err == -EBUSY)
            fprintf(stderr,
                    "attach: interface already has an XDP program; refusing to "
                    "replace it (would clobber the firewall dataplane)\n");
        else
            fprintf(stderr, "attach failed: %s\n", strerror(-err));
        return -1;
    }
    return prog_fd;
}

/*
 * #4906 HC-101 / #6289 M1: detach only our own program, and only if it is still
 * ours, on both interfaces we attached to. XDP_FLAGS_REPLACE + old_prog_fd makes
 * the kernel refuse if something else now owns the hook. Shared by the normal
 * exit path AND the early umem/alloc-failure exits so a failed setup never leaks
 * our attached program on the owner (and possibly secondary) interface.
 */
static void detach_ours(int ifindex, int sec_ifindex, int sec_attached,
                        int prog_fd)
{
    LIBBPF_OPTS(bpf_xdp_attach_opts, dopts, .old_prog_fd = prog_fd);
    if (bpf_xdp_detach(ifindex, XDP_FLAGS_REPLACE, &dopts))
        fprintf(stderr, "  owner XDP detach skipped/failed — hook not ours\n");
    if (sec_attached &&
        bpf_xdp_detach(sec_ifindex, XDP_FLAGS_REPLACE, &dopts))
        fprintf(stderr, "  secondary XDP detach skipped/failed — hook not ours\n");
}

/*
 * #4906 HC-069: drain up to BATCH_SIZE descriptors from an RX ring, count them,
 * and recycle the chunk-aligned frame bases back to `fill`. The previous code
 * released the RX descriptors BEFORE reading them and used xsk_ring_cons__comp_addr
 * (the completion-ring layout) on the RX ring — recycling stale/wrong offsets
 * into the fill ring (fill-ring starvation / duplicate frame ownership). Read
 * the addresses via the RX-descriptor accessor first, then release, then mask to
 * the frame base before returning them. rcvd is bounded by BATCH_SIZE.
 */
static unsigned int drain_rx(struct xsk_ring_cons *rx, struct xsk_ring_prod *fill)
{
    __u32 idx_rx = 0;
    unsigned int rcvd = xsk_ring_cons__peek(rx, BATCH_SIZE, &idx_rx);
    if (rcvd == 0)
        return 0;
    __u64 addrs[BATCH_SIZE];
    for (unsigned int i = 0; i < rcvd; i++)
        addrs[i] = xsk_ring_cons__rx_desc(rx, idx_rx + i)->addr;
    xsk_ring_cons__release(rx, rcvd);
    __u32 idx_fq;
    if (xsk_ring_prod__reserve(fill, rcvd, &idx_fq) == rcvd) {
        for (unsigned int i = 0; i < rcvd; i++)
            *xsk_ring_prod__fill_addr(fill, idx_fq + i) =
                addrs[i] & ~((__u64)FRAME_SIZE - 1);
        xsk_ring_prod__submit(fill, rcvd);
    }
    return rcvd;
}

/* Prime a per-socket fill ring with `count` frames starting at frame index
 * `base` (so the owner and secondary sockets own disjoint UMEM chunks and never
 * double-own a frame on the shared UMEM). Returns 1 on success. */
static int prime_fill(struct xsk_ring_prod *fill, int base, int count,
                      const char *who)
{
    __u32 idx;
    if (xsk_ring_prod__reserve(fill, count, &idx) != (unsigned)count) {
        printf("  fill ring (%s) reserve FAILED\n", who);
        return 0;
    }
    for (int i = 0; i < count; i++)
        *xsk_ring_prod__fill_addr(fill, idx + i) = (__u64)(base + i) * FRAME_SIZE;
    xsk_ring_prod__submit(fill, count);
    printf("  fill ring (%s) primed: %d frames from base %d\n", who, count, base);
    return 1;
}

static unsigned long test_phase(const char *label, const char *iface,
    int queue, const char *secondary_iface, int secondary_queue,
    int map_fd, int use_copy, struct xsk_umem *umem,
    struct xsk_ring_prod *umem_fill, struct xsk_ring_cons *umem_comp,
    void *umem_area, unsigned long *secondary_rx_out)
{
    printf("\n=== %s ===\n", label);
    (void)umem_fill;
    (void)umem_comp;
    (void)umem_area;
    *secondary_rx_out = 0;

    /* Per-socket rings for create_shared */
    struct xsk_ring_cons rx;
    struct xsk_ring_prod tx;
    struct xsk_ring_prod fill;
    struct xsk_ring_cons comp;
    struct xsk_socket *xsk = NULL;
    struct xsk_ring_cons secondary_rx;
    struct xsk_ring_prod secondary_tx;
    struct xsk_ring_prod secondary_fill;
    struct xsk_ring_cons secondary_comp;
    struct xsk_socket *secondary_xsk = NULL;
    int secondary_fd = -1;

    struct xsk_socket_config cfg = {
        .rx_size = NUM_FRAMES,
        .tx_size = 256,
        .bind_flags = XDP_USE_NEED_WAKEUP | (use_copy ? XDP_COPY : XDP_ZEROCOPY),
        .libxdp_flags = XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD,
        .xdp_flags = 0,
    };

    int err = xsk_socket__create_shared(&xsk, iface, queue, umem,
                                         &rx, &tx, &fill, &comp, &cfg);
    if (err) {
        fprintf(stderr, "  create_shared failed: %s (rc=%d)\n", strerror(-err), err);
        return 0;
    }
    int xsk_fd = xsk_socket__fd(xsk);
    printf("  create_shared ok, fd=%d %s\n", xsk_fd, use_copy ? "copy" : "zerocopy");
    int zc = xsk_reports_zerocopy(xsk_fd);
    printf("  owner XDP_OPTIONS_ZEROCOPY=%d\n", zc);
    if (!use_copy && zc != 1) {
        fprintf(stderr, "  owner did not report zero-copy after bind\n");
        xsk_socket__delete(xsk);
        return 0;
    }

    if (secondary_iface) {
        struct xsk_socket_config secondary_cfg = {
            .rx_size = NUM_FRAMES,
            .tx_size = 256,
            .bind_flags = XDP_SHARED_UMEM,
            .libxdp_flags = XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD,
            .xdp_flags = 0,
        };
        err = xsk_socket__create_shared(&secondary_xsk, secondary_iface,
                                        secondary_queue, umem,
                                        &secondary_rx, &secondary_tx,
                                        &secondary_fill, &secondary_comp,
                                        &secondary_cfg);
        if (err) {
            fprintf(stderr,
                    "  secondary create_shared(flags=XDP_SHARED_UMEM) failed: %s (rc=%d)\n",
                    strerror(-err), err);
            xsk_socket__delete(xsk);
            return 0;
        }
        secondary_fd = xsk_socket__fd(secondary_xsk);
        int secondary_zc = xsk_reports_zerocopy(secondary_fd);
        printf("  secondary create_shared ok iface=%s queue=%d fd=%d flags=0x%x zerocopy=%d\n",
               secondary_iface, secondary_queue, secondary_fd, XDP_SHARED_UMEM,
               secondary_zc);
        printf("  secondary rings rx_size=%u tx_size=%u fill_size=%u comp_size=%u\n",
               secondary_rx.size, secondary_tx.size, secondary_fill.size,
               secondary_comp.size);
        if (!use_copy && secondary_zc != 1) {
            fprintf(stderr, "  secondary did not report zero-copy after bind\n");
            xsk_socket__delete(secondary_xsk);
            xsk_socket__delete(xsk);
            return 0;
        }
    }

    /* Register both sockets in the xskmap so packets on their respective queues
     * are redirected to them. */
    __u32 key = queue, val = xsk_fd;
    bpf_map_update_elem(map_fd, &key, &val, 0);
    printf("  xskmap[%u] = fd %d\n", key, xsk_fd);
    __u32 skey = secondary_queue;
    if (secondary_xsk) {
        __u32 sval = secondary_fd;
        bpf_map_update_elem(map_fd, &skey, &sval, 0);
        printf("  xskmap[%u] = fd %d (secondary)\n", skey, secondary_fd);
    }

    /* Prime the per-socket fill rings from DISJOINT halves of the shared UMEM so
     * the owner and secondary never hand the kernel the same frame. With no
     * secondary the owner uses the whole UMEM. */
    int owner_frames = secondary_xsk ? NUM_FRAMES / 2 : NUM_FRAMES;
    prime_fill(&fill, 0, owner_frames, "owner");
    if (secondary_xsk)
        prime_fill(&secondary_fill, NUM_FRAMES / 2, NUM_FRAMES / 2, "secondary");

    /* Kick NAPI on both sockets */
    for (int i = 0; i < 20; i++) {
        struct pollfd pfd = { .fd = xsk_fd, .events = POLLIN };
        poll(&pfd, 1, 1);
        sendto(xsk_fd, NULL, 0, MSG_DONTWAIT, NULL, 0);
        if (secondary_fd >= 0)
            sendto(secondary_fd, NULL, 0, MSG_DONTWAIT, NULL, 0);
    }

    /* Receive for 3 seconds, draining BOTH sockets. #4906 HC-095: the secondary
     * socket is actually polled and its receive count is reported and folded
     * into PASS/FAIL — previously it was created but never read, so PASS
     * reflected only the owner. */
    struct timespec start, now;
    clock_gettime(CLOCK_MONOTONIC, &start);
    unsigned long total = 0, secondary_total = 0, polls = 0;

    while (1) {
        clock_gettime(CLOCK_MONOTONIC, &now);
        if ((now.tv_sec - start.tv_sec) + (now.tv_nsec - start.tv_nsec)/1e9 >= 3.0)
            break;

        unsigned int got = drain_rx(&rx, &fill);
        unsigned int got2 = 0;
        if (secondary_xsk)
            got2 = drain_rx(&secondary_rx, &secondary_fill);
        total += got;
        secondary_total += got2;

        if (got == 0 && got2 == 0) {
            polls++;
            struct pollfd pfds[2];
            int nfds = 1;
            pfds[0].fd = xsk_fd; pfds[0].events = POLLIN; pfds[0].revents = 0;
            if (secondary_fd >= 0) {
                pfds[1].fd = secondary_fd; pfds[1].events = POLLIN; pfds[1].revents = 0;
                nfds = 2;
            }
            poll(pfds, nfds, 10);
        }
    }

    printf("  rx=%lu secondary_rx=%lu empty_polls=%lu\n",
           total, secondary_total, polls);
    *secondary_rx_out = secondary_total;

    /* Cleanup */
    bpf_map_delete_elem(map_fd, &key);
    if (secondary_xsk)
        bpf_map_delete_elem(map_fd, &skey);
    if (secondary_xsk)
        xsk_socket__delete(secondary_xsk);
    xsk_socket__delete(xsk);
    return total;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr,
                "Usage: %s <owner-iface> <owner-queue> [secondary-iface secondary-queue] [copy|zerocopy]\n",
                argv[0]);
        return 1;
    }
    const char *iface = argv[1];
    int queue = atoi(argv[2]);
    const char *secondary_iface = NULL;
    int secondary_queue = queue;
    int mode_arg = 3;
    if (argc > 4 && strcmp(argv[3], "copy") != 0 && strcmp(argv[3], "zerocopy") != 0) {
        secondary_iface = argv[3];
        secondary_queue = atoi(argv[4]);
        mode_arg = 5;
    }
    int use_copy = (argc > mode_arg && strcmp(argv[mode_arg], "copy") == 0);
    int ifindex = if_nametoindex(iface);
    if (!ifindex) {
        fprintf(stderr, "interface %s not found\n", iface);
        return 1;
    }
    int sec_ifindex = 0;
    if (secondary_iface) {
        sec_ifindex = if_nametoindex(secondary_iface);
        if (!sec_ifindex) {
            fprintf(stderr, "secondary interface %s not found\n", secondary_iface);
            return 1;
        }
    }

    printf("=== xsk_socket__create_shared test ===\n");
    printf("interface=%s queue=%d mode=%s\n", iface, queue,
           use_copy ? "copy" : "zerocopy");
    if (secondary_iface)
        printf("secondary_interface=%s secondary_queue=%d secondary_flags=XDP_SHARED_UMEM\n",
               secondary_iface, secondary_queue);

    /* Load XDP program (attaches to the owner interface). Capture prog_fd so we
     * can (a) attach the same program to a distinct secondary interface and
     * (b) detach only our own program on exit (#4906 HC-101). */
    int map_fd;
    int prog_fd = load_xdp(ifindex, &map_fd);
    if (prog_fd < 0) return 1;

    /* #4906 HC-095: for a secondary on a DIFFERENT interface, that interface
     * needs the redirect program too, otherwise the secondary socket can never
     * receive and the test would falsely FAIL. Attach with UPDATE_IF_NOEXIST so
     * we never clobber an existing program there. */
    int sec_attached = 0;
    if (sec_ifindex && sec_ifindex != ifindex) {
        int e = bpf_xdp_attach(sec_ifindex, prog_fd, XDP_FLAGS_UPDATE_IF_NOEXIST, NULL);
        if (e)
            fprintf(stderr,
                    "  secondary iface XDP attach failed/busy (%s); secondary "
                    "may not receive\n", strerror(-e));
        else
            sec_attached = 1;
    }

    /* Create UMEM */
    void *umem_area = aligned_alloc(getpagesize(), NUM_FRAMES * FRAME_SIZE);
    /* #6289 M1: aligned_alloc() can return NULL. An unchecked NULL flows into
     * xsk_umem__create below and, on its failure, the old code did `return 1`
     * WITHOUT reaching the detach — leaking OUR program on the owner (and any
     * secondary) interface. Detach before exiting. */
    if (!umem_area) {
        fprintf(stderr, "umem_area alloc failed\n");
        detach_ours(ifindex, sec_ifindex, sec_attached, prog_fd);
        return 1;
    }
    struct xsk_ring_prod umem_fill;
    struct xsk_ring_cons umem_comp;
    struct xsk_umem *umem;
    struct xsk_umem_config ucfg = {
        .fill_size = NUM_FRAMES,
        .comp_size = NUM_FRAMES,
        .frame_size = FRAME_SIZE,
        .frame_headroom = 256,
    };
    if (xsk_umem__create(&umem, umem_area,
                          (unsigned long long)NUM_FRAMES * FRAME_SIZE,
                          &umem_fill, &umem_comp, &ucfg)) {
        /* #6289 M1: detach our program (and free the UMEM area) before exiting
         * so the umem-failure path does not leak it on the interface(s). */
        fprintf(stderr, "umem create failed\n");
        free(umem_area);
        detach_ours(ifindex, sec_ifindex, sec_attached, prog_fd);
        return 1;
    }
    printf("umem created\n");

    /* Start traffic */
    pid_t child = fork();
    if (child < 0) {
        /* #4906 HC-001: fork() failed. Do NOT fall into the unguarded
         * kill(child, 9) below — with child == -1 that is kill(-1, SIGKILL),
         * a host-wide SIGKILL as root. Warn and run without background
         * traffic; the guarded kill skips for child <= 0. */
        perror("fork (background traffic)");
    } else if (child == 0) {
        char ifarg[64];
        snprintf(ifarg, sizeof(ifarg), "-I%s", iface);
        execlp("ping", "ping", ifarg, "-i", "0.1", "-c", "50", "-q",
               "10.0.61.1", NULL);
        _exit(1);
    }

    /* Phase 1: create_shared */
    unsigned long secondary_rx = 0;
    unsigned long rx1 = test_phase("Phase 1: create_shared (initial)",
        iface, queue, secondary_iface, secondary_queue, map_fd, use_copy, umem,
        &umem_fill, &umem_comp, umem_area, &secondary_rx);

    /* #4906 HC-001: only signal a real child — guard against kill(-1, SIGKILL)
     * on a fork() failure (child < 0). */
    if (child > 0) {
        kill(child, 9);
        waitpid(child, NULL, 0);
    }

    /* #4906 HC-101 / #6289 M1: detach only our own program, and only if still
     * ours, on both interfaces we attached to (see detach_ours — the same path
     * the early umem/alloc-failure exits take). */
    detach_ours(ifindex, sec_ifindex, sec_attached, prog_fd);
    xsk_umem__delete(umem);
    free(umem_area);

    /* #4906 HC-095: PASS requires the owner to receive AND, when a secondary is
     * configured, the secondary to receive too — the shared-UMEM claim is only
     * proven if the secondary socket actually gets packets. */
    printf("\n");
    int pass;
    if (secondary_iface) {
        pass = (rx1 > 0 && secondary_rx > 0);
        printf("RESULT: %s  owner_rx=%lu secondary_rx=%lu\n",
               pass ? "PASS" : "FAIL", rx1, secondary_rx);
    } else {
        pass = (rx1 > 0);
        printf("RESULT: %s  create_shared rx=%lu\n",
               pass ? "PASS" : "FAIL", rx1);
    }

    return pass ? 0 : 1;
}
